import {
  AlertTriangle,
  ArrowRight,
  BarChart3,
  BookOpen,
  Box,
  Brain,
  Bug,
  CheckCircle2,
  Circle,
  Clock,
  Cloud,
  Code2,
  Database,
  FileCode,
  Filter,
  Flag,
  Folder,
  Globe,
  Heart,
  Keyboard,
  Layers,
  Lightbulb,
  Link2,
  ListChecks,
  Lock,
  LucideIcon,
  MessageCircle,
  Monitor,
  Network,
  Play,
  Puzzle,
  Repeat,
  Rocket,
  Search,
  Server,
  Settings,
  Shield,
  Shuffle,
  Sparkles,
  SquareTerminal,
  Star,
  Target,
  Users,
  Wrench,
  Zap,
} from 'lucide-react';

// The closed icon vocabulary, shared by every scene that takes an icon name
// from the pipeline. Go owns the list (pointIconVocab in storyboard.go) and
// normalizes anything outside it to "dot", so this map is exhaustive by
// construction — but iconFor still falls back, because a scene graph written
// before a name was added should not render a hole.

export const ICONS: Record<string, LucideIcon> = {
  idea: Lightbulb,
  code: Code2,
  rocket: Rocket,
  book: BookOpen,
  check: CheckCircle2,
  alert: AlertTriangle,
  list: ListChecks,
  box: Box,
  arrow: ArrowRight,
  terminal: SquareTerminal,
  database: Database,
  globe: Globe,
  clock: Clock,
  star: Star,
  search: Search,
  play: Play,
  layers: Layers,
  link: Link2,
  zap: Zap,
  shield: Shield,
  target: Target,
  gear: Settings,
  heart: Heart,
  flag: Flag,
  brain: Brain,
  sparkles: Sparkles,
  puzzle: Puzzle,
  wrench: Wrench,
  folder: Folder,
  message: MessageCircle,
  repeat: Repeat,
  bug: Bug,
  file: FileCode,
  keyboard: Keyboard,
  monitor: Monitor,
  server: Server,
  cloud: Cloud,
  lock: Lock,
  users: Users,
  chart: BarChart3,
  shuffle: Shuffle,
  filter: Filter,
  network: Network,
  dot: Circle,
};

/** The icon for a vocabulary name, falling back to the neutral dot. */
export const iconFor = (name: string | undefined): LucideIcon =>
  (name && ICONS[name]) || ICONS.dot;
