import {
  AlertTriangle,
  ArrowRight,
  Atom,
  BarChart3,
  BookOpen,
  Box,
  Brain,
  Bug,
  Building2,
  CheckCircle2,
  Circle,
  Clock,
  Cloud,
  Code2,
  Compass,
  Database,
  FileCode,
  Filter,
  Flag,
  Folder,
  Globe,
  GraduationCap,
  Heart,
  Infinity as InfinityIcon,
  Keyboard,
  Layers,
  Lightbulb,
  Link2,
  ListChecks,
  Lock,
  LucideIcon,
  Map as MapIcon,
  MessageCircle,
  Milestone,
  Monitor,
  Mountain,
  Network,
  Orbit,
  Play,
  Puzzle,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  Ruler,
  Search,
  Server,
  Settings,
  Shield,
  Shuffle,
  Signpost,
  Sparkles,
  Sprout,
  SquareTerminal,
  Star,
  Target,
  Telescope,
  Trophy,
  Users,
  Wrench,
  Zap,
} from 'lucide-react';

// The closed icon vocabulary, shared by every scene that takes an icon name
// from the pipeline. Go owns the list (pointIconVocab in storyboard.go) and
// normalizes anything outside it to "dot", so this map is exhaustive by
// construction — but iconFor still falls back, because a scene graph written
// before a name was added should not render a hole.

export const ICONS: Record<string, LucideIcon> = {
  idea: Lightbulb,
  code: Code2,
  rocket: Rocket,
  book: BookOpen,
  check: CheckCircle2,
  alert: AlertTriangle,
  list: ListChecks,
  box: Box,
  arrow: ArrowRight,
  terminal: SquareTerminal,
  database: Database,
  globe: Globe,
  clock: Clock,
  star: Star,
  search: Search,
  play: Play,
  layers: Layers,
  link: Link2,
  zap: Zap,
  shield: Shield,
  target: Target,
  gear: Settings,
  heart: Heart,
  flag: Flag,
  brain: Brain,
  sparkles: Sparkles,
  puzzle: Puzzle,
  wrench: Wrench,
  folder: Folder,
  message: MessageCircle,
  repeat: Repeat,
  bug: Bug,
  file: FileCode,
  keyboard: Keyboard,
  monitor: Monitor,
  server: Server,
  cloud: Cloud,
  lock: Lock,
  users: Users,
  chart: BarChart3,
  shuffle: Shuffle,
  filter: Filter,
  network: Network,
  // A journey and its landmarks. The set above was built for architecture
  // diagrams and had a load balancer but nothing for "you are three parts into
  // a course", which is the whole subject of the chapter template.
  compass: Compass,
  map: MapIcon,
  signpost: Signpost,
  milestone: Milestone,
  trophy: Trophy,
  graduate: GraduationCap,
  // Things that come back round.
  orbit: Orbit,
  refresh: RefreshCw,
  recycle: Recycle,
  sprout: Sprout,
  infinity: InfinityIcon,
  // Things at a size. A ladder of magnitudes wants objects the eye can rank
  // without reading the label under them.
  ruler: Ruler,
  mountain: Mountain,
  atom: Atom,
  telescope: Telescope,
  city: Building2,
  dot: Circle,
};

/** The icon for a vocabulary name, falling back to the neutral dot. */
export const iconFor = (name: string | undefined): LucideIcon =>
  (name && ICONS[name]) || ICONS.dot;
