// @ts-nocheck
// GENERATED by port-lumen.mjs — do not edit by hand.
// Source of truth: demo/lumen/{css/style.css,js/data.js,js/app.js}

export let BASE = '/lumen/';
export const setBase = (b) => { BASE = b; };

export const CSS = String.raw`
/* Lumen.
 *
 * The chrome is deliberately colourless: paper, ink, and hairlines. Every photo
 * in the feed brings its own palette, and an app that also brings one ends up
 * fighting its own content. So buttons are ink, the active nav item is ink, and
 * the only saturated thing on screen is the like state.
 */

:root {
  --paper:  #FFFFFF;
  --sheet:  #FBFBFC;
  --ink:    #0D0F12;
  --ink-2:  #4A5058;
  --ink-3:  #8A9099;
  --ink-4:  #B9BEC5;
  --line:   #E9EAEE;
  --line-2: #F2F3F5;
  --like:   #E8384F;
  --r:      14px;
  --ui: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Geist", system-ui, sans-serif;
  --ui-display: "SF Pro Display", -apple-system, "Geist", system-ui, sans-serif;

  --shadow-1: 0 1px 2px rgba(13,15,18,.04), 0 4px 14px rgba(13,15,18,.045);
  --shadow-2: 0 2px 6px rgba(13,15,18,.06), 0 18px 48px rgba(13,15,18,.10);
  --shadow-3: 0 30px 90px rgba(13,15,18,.22);
}

:where(.app, .app *) { box-sizing: border-box; margin: 0; padding: 0; }

.app {
  min-height: 100%;
  background: var(--sheet);
  color: var(--ink);
  font-family: var(--ui);
  font-size: 15px;
  line-height: 1.45;
  -webkit-font-smoothing: antialiased;
}

:where(.app button) { font: inherit; color: inherit; background: none; border: 0; cursor: pointer; }
:where(.app img) { display: block; }
:where(.app a) { color: inherit; text-decoration: none; }

:where(.app) ::selection { background: #0D0F12; color: #fff; }

/* ---------------------------------------------------------------- shell */

.app { display: flex; min-height: 100vh; }

.side {
  position: sticky; top: 0; align-self: flex-start;
  width: 244px; flex: none; height: 100vh;
  padding: 26px 16px 18px;
  background: var(--paper);
  border-right: 1px solid var(--line);
  display: flex; flex-direction: column;
}

.brand { display: flex; align-items: center; gap: 10px; padding: 0 10px 26px; }
.brand svg { flex: none; }
.brand b {
  font-size: 23px; font-weight: 700; letter-spacing: -.035em;
  font-family: var(--ui-display);
}

.nav { display: flex; flex-direction: column; gap: 2px; }
.nav button {
  display: flex; align-items: center; gap: 13px;
  padding: 10px 11px; border-radius: 11px;
  font-size: 15.5px; font-weight: 500; color: var(--ink-2);
  transition: background .14s ease, color .14s ease;
}
.nav button svg { flex: none; }
.nav button:hover { background: var(--line-2); color: var(--ink); }
.nav button.on { color: var(--ink); font-weight: 650; background: #F0F1F3; }
.nav .dot {
  margin-left: auto; width: 7px; height: 7px; border-radius: 50%;
  background: var(--like);
}

.side .spacer { flex: 1; }

.me-row {
  display: flex; align-items: center; gap: 11px;
  padding: 9px 10px; border-radius: 11px;
}
.me-row:hover { background: var(--line-2); }
.me-row img { width: 32px; height: 32px; border-radius: 50%; }
.me-row .who { min-width: 0; }
.me-row .who b { display: block; font-size: 14px; font-weight: 600; letter-spacing: -.01em; }
.me-row .who span { display: block; font-size: 12.5px; color: var(--ink-3); }

/* ---------------------------------------------------------------- main */

.main { flex: 1; min-width: 0; display: flex; justify-content: center; gap: 40px; padding: 0 40px; }
.col { width: 618px; flex: none; padding: 30px 0 90px; }
.rail { width: 300px; flex: none; padding: 34px 0 90px; }

.head { display: flex; align-items: baseline; justify-content: space-between; margin-bottom: 22px; }
.head h1 { font-size: 27px; font-weight: 700; letter-spacing: -.032em; }
.head .sub { font-size: 13px; color: var(--ink-3); }

/* ---------------------------------------------------------------- stories */

.stories {
  display: flex; gap: 20px; overflow: hidden;
  background: var(--paper); border: 1px solid var(--line);
  border-radius: var(--r); padding: 17px 20px; margin-bottom: 26px;
  box-shadow: var(--shadow-1);
}
.story { width: 62px; flex: none; text-align: center; }
.story .ring {
  width: 62px; height: 62px; border-radius: 50%; padding: 2.5px;
  background: var(--ink); position: relative;
}
.story.seen .ring { background: var(--line); }
.story.mine .ring { background: var(--line-2); border: 1.5px dashed var(--ink-4); padding: 1px; }
.story .ring img { width: 100%; height: 100%; border-radius: 50%; border: 2.5px solid var(--paper); }
.story .plus {
  position: absolute; right: -2px; bottom: -2px;
  width: 21px; height: 21px; border-radius: 50%;
  background: var(--ink); color: #fff; border: 2.5px solid var(--paper);
  display: grid; place-items: center; font-size: 14px; line-height: 1; font-weight: 500;
}
.story span {
  display: block; margin-top: 8px; font-size: 11.5px; color: var(--ink-2);
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}

/* ---------------------------------------------------------------- post */

.post {
  background: var(--paper); border: 1px solid var(--line);
  border-radius: var(--r); margin-bottom: 26px; overflow: hidden;
  box-shadow: var(--shadow-1);
}
.post-top { display: flex; align-items: center; gap: 11px; padding: 13px 15px; }
.post-top img.av { width: 36px; height: 36px; border-radius: 50%; }
.post-top .who b { font-size: 14.5px; font-weight: 650; letter-spacing: -.012em; }
.post-top .who span { display: block; font-size: 12.5px; color: var(--ink-3); }
.post-top .more { margin-left: auto; color: var(--ink-3); padding: 4px 6px; border-radius: 8px; }
.post-top .more:hover { background: var(--line-2); color: var(--ink); }

.frame { position: relative; background: var(--line-2); aspect-ratio: 1 / 1; }
.frame img { width: 100%; height: 100%; object-fit: cover; }

.acts { display: flex; align-items: center; gap: 4px; padding: 11px 11px 4px; }
.acts button {
  padding: 7px; border-radius: 10px; color: var(--ink);
  transition: background .14s ease, transform .1s ease;
}
.acts button:hover { background: var(--line-2); }
.acts button:active { transform: scale(.9); }
.acts button.liked { color: var(--like); }
.acts .save { margin-left: auto; }

.post-body { padding: 2px 15px 15px; }
.likes { font-size: 14px; font-weight: 650; letter-spacing: -.012em; }
.cap { margin-top: 5px; font-size: 14.5px; }
.cap b { font-weight: 650; margin-right: 6px; }
.tags { margin-top: 4px; font-size: 14px; color: var(--ink-2); }
.tags span { margin-right: 8px; }
.cmts { margin-top: 9px; display: flex; flex-direction: column; gap: 4px; }
.cmts .c { font-size: 14px; }
.cmts .c b { font-weight: 650; margin-right: 6px; }
.more-c { margin-top: 7px; font-size: 13.5px; color: var(--ink-3); }
.more-c:hover { color: var(--ink); }

.add-c {
  display: flex; align-items: center; gap: 10px;
  border-top: 1px solid var(--line-2); padding: 11px 15px;
}
.add-c input {
  flex: 1; border: 0; outline: 0; background: none;
  font: inherit; font-size: 14.5px; color: var(--ink);
}
.add-c input::placeholder { color: var(--ink-4); }
.add-c .send { font-size: 14px; font-weight: 650; color: var(--ink-4); }
.add-c .send.on { color: var(--ink); }

/* ---------------------------------------------------------------- rail */

.rail-card {
  background: var(--paper); border: 1px solid var(--line);
  border-radius: var(--r); padding: 16px; margin-bottom: 18px;
  box-shadow: var(--shadow-1);
}
.rail-card h3 {
  font-size: 12px; font-weight: 650; letter-spacing: .07em;
  text-transform: uppercase; color: var(--ink-3); margin-bottom: 13px;
}
.sug { display: flex; align-items: center; gap: 11px; padding: 7px 0; }
.sug img { width: 36px; height: 36px; border-radius: 50%; }
.sug .who { min-width: 0; flex: 1; }
.sug .who b { display: block; font-size: 13.5px; font-weight: 600; letter-spacing: -.01em; }
.sug .who span { display: block; font-size: 12px; color: var(--ink-3); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.btn-follow { font-size: 13.5px; font-weight: 650; }
.btn-follow.no { color: var(--ink); }
.btn-follow.yes { color: var(--ink-3); }

.notif { display: flex; gap: 11px; padding: 8px 0; align-items: flex-start; }
.notif img { width: 32px; height: 32px; border-radius: 50%; flex: none; }
.notif p { font-size: 13.5px; line-height: 1.4; }
.notif p b { font-weight: 650; }
.notif p em { font-style: normal; color: var(--ink-3); }

.foot { padding: 4px 4px 0; font-size: 12px; color: var(--ink-4); line-height: 1.7; }

/* ---------------------------------------------------------------- explore */

.grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 5px; }
.grid .cell { position: relative; aspect-ratio: 1/1; overflow: hidden; background: var(--line-2); }
.grid .cell img { width: 100%; height: 100%; object-fit: cover; transition: transform .35s ease; }
.grid .cell:hover img { transform: scale(1.045); }
.grid .cell .veil {
  position: absolute; inset: 0; background: rgba(13,15,18,.42);
  opacity: 0; transition: opacity .2s ease;
  display: flex; align-items: center; justify-content: center; gap: 22px;
  color: #fff; font-weight: 650; font-size: 15px;
}
.grid .cell:hover .veil { opacity: 1; }
.grid .cell .veil span { display: flex; align-items: center; gap: 7px; }
.grid .cell.tall { grid-row: span 2; aspect-ratio: 1/2.01; }

.chips { display: flex; gap: 8px; margin-bottom: 20px; flex-wrap: wrap; }
.chip {
  padding: 7px 15px; border-radius: 999px; border: 1px solid var(--line);
  background: var(--paper); font-size: 13.5px; font-weight: 550; color: var(--ink-2);
}
.chip:hover { border-color: var(--ink-4); color: var(--ink); }
.chip.on { background: var(--ink); border-color: var(--ink); color: #fff; }

/* ---------------------------------------------------------------- profile */

.prof { display: flex; gap: 46px; align-items: center; padding: 6px 0 34px; }
.prof .big { width: 132px; height: 132px; border-radius: 50%; flex: none; box-shadow: var(--shadow-1); }
.prof .meta { flex: 1; }
.prof .row1 { display: flex; align-items: center; gap: 16px; }
.prof .row1 h2 { font-size: 22px; font-weight: 650; letter-spacing: -.02em; }
.btn {
  padding: 8px 17px; border-radius: 10px; font-size: 14px; font-weight: 600;
  background: var(--ink); color: #fff;
}
.btn.ghost { background: var(--paper); color: var(--ink); border: 1px solid var(--line); }
.btn.ghost:hover { border-color: var(--ink-4); }
.stats { display: flex; gap: 34px; margin: 18px 0 14px; }
.stats div { font-size: 14.5px; color: var(--ink-2); }
.stats b { color: var(--ink); font-weight: 650; }
.prof .name { font-weight: 650; font-size: 14.5px; }
.prof .bio { font-size: 14.5px; color: var(--ink-2); }

.tabs { display: flex; gap: 40px; border-top: 1px solid var(--line); margin-bottom: 5px; }
.tabs button {
  padding: 15px 2px; font-size: 12px; font-weight: 650; letter-spacing: .08em;
  text-transform: uppercase; color: var(--ink-3); border-top: 1.5px solid transparent;
  margin-top: -1px; display: flex; align-items: center; gap: 7px;
}
.tabs button.on { color: var(--ink); border-top-color: var(--ink); }

/* ---------------------------------------------------------------- messages */

.dm { display: flex; background: var(--paper); border: 1px solid var(--line);
      border-radius: var(--r); overflow: hidden; height: 680px; box-shadow: var(--shadow-1); }
.dm-list { width: 268px; flex: none; border-right: 1px solid var(--line); overflow: hidden; }
.dm-list .t { padding: 12px 15px; display: flex; gap: 11px; align-items: center; }
.dm-list .t:hover { background: var(--sheet); }
.dm-list .t.on { background: #F0F1F3; }
.dm-list .t img { width: 40px; height: 40px; border-radius: 50%; }
.dm-list .t .who { min-width: 0; flex: 1; }
.dm-list .t .who b { display: block; font-size: 14px; font-weight: 600; }
.dm-list .t .who span { display: block; font-size: 12.5px; color: var(--ink-3); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.dm-list .t .when { font-size: 11.5px; color: var(--ink-4); align-self: flex-start; margin-top: 3px; }

.dm-pane { flex: 1; display: flex; flex-direction: column; min-width: 0; }
.dm-head { padding: 13px 18px; border-bottom: 1px solid var(--line); display: flex; align-items: center; gap: 11px; }
.dm-head img { width: 34px; height: 34px; border-radius: 50%; }
.dm-head b { font-size: 14.5px; font-weight: 650; }
.dm-body { flex: 1; padding: 20px 18px; display: flex; flex-direction: column; gap: 9px; justify-content: flex-end; }
.bub { max-width: 74%; padding: 9px 14px; border-radius: 17px; font-size: 14.5px; }
.bub.them { background: var(--line-2); align-self: flex-start; border-bottom-left-radius: 6px; }
.bub.me { background: var(--ink); color: #fff; align-self: flex-end; border-bottom-right-radius: 6px; }
.dm-foot { padding: 13px 18px; border-top: 1px solid var(--line); display: flex; gap: 12px; align-items: center; }
.dm-foot input { flex: 1; border: 1px solid var(--line); border-radius: 999px; padding: 9px 16px; font: inherit; font-size: 14.5px; outline: 0; }
.dm-foot input:focus { border-color: var(--ink-4); }

/* ---------------------------------------------------------------- composer */

.comp { display: flex; gap: 30px; }
.comp .stage {
  width: 520px; flex: none; aspect-ratio: 1/1; border-radius: var(--r);
  overflow: hidden; background: var(--paper); border: 1px solid var(--line);
  display: grid; place-items: center; position: relative; box-shadow: var(--shadow-1);
}
.comp .stage img { width: 100%; height: 100%; object-fit: cover; }
.comp .drop { text-align: center; color: var(--ink-3); padding: 40px; }
.comp .drop svg { margin: 0 auto 16px; }
.comp .drop b { display: block; font-size: 17px; font-weight: 600; color: var(--ink); margin-bottom: 6px; }
.comp .drop p { font-size: 14px; }
.comp .panel { flex: 1; min-width: 0; }
.comp label { display: block; font-size: 12px; font-weight: 650; letter-spacing: .07em;
              text-transform: uppercase; color: var(--ink-3); margin: 0 0 9px; }
.comp textarea, .comp input[type=text] {
  width: 100%; border: 1px solid var(--line); border-radius: 11px; padding: 12px 14px;
  font: inherit; font-size: 14.5px; outline: 0; resize: none; background: var(--paper);
}
.comp textarea:focus, .comp input[type=text]:focus { border-color: var(--ink-4); }
.comp .field { margin-bottom: 20px; }
.filters { display: flex; gap: 9px; overflow: hidden; }
.filters .f { text-align: center; }
.filters .f .sw { width: 58px; height: 58px; border-radius: 10px; overflow: hidden; border: 2px solid transparent; }
.filters .f.on .sw { border-color: var(--ink); }
.filters .f .sw img { width: 100%; height: 100%; object-fit: cover; }
.filters .f span { display: block; margin-top: 6px; font-size: 11px; color: var(--ink-3); }
.filters .f.on span { color: var(--ink); font-weight: 600; }
.comp .go { width: 100%; padding: 12px; border-radius: 11px; background: var(--ink); color: #fff;
            font-size: 15px; font-weight: 650; margin-top: 6px; }
.comp .go[disabled] { background: var(--line); color: var(--ink-4); cursor: default; }

/* ---------------------------------------------------------------- lightbox */

.lb { position: fixed; inset: 0; background: rgba(13,15,18,.72); z-index: 50;
      display: grid; place-items: center; padding: 40px; backdrop-filter: blur(3px); }
.lb .sheet { display: flex; background: var(--paper); border-radius: 16px; overflow: hidden;
             max-width: 1140px; width: 100%; height: 660px; box-shadow: var(--shadow-3); }
.lb .pic { flex: 1; background: #0D0F12; }
.lb .pic img { width: 100%; height: 100%; object-fit: contain; }
.lb .side-pane { width: 396px; flex: none; display: flex; flex-direction: column; border-left: 1px solid var(--line); }
.lb .side-pane .list { flex: 1; overflow: hidden; padding: 4px 16px 12px; }
.lb .x { position: absolute; right: 26px; top: 22px; color: #fff; font-size: 26px; line-height: 1; }

/* a photo landing in the feed after the composer posts it */
@keyframes rise { from { opacity: 0; transform: translateY(16px) scale(.99); } to { opacity: 1; transform: none; } }
.fresh { animation: rise .42s cubic-bezier(.22,1,.36,1) both; }

.toast {
  position: fixed; left: 50%; bottom: 34px; transform: translateX(-50%);
  background: var(--ink); color: #fff; padding: 11px 20px; border-radius: 999px;
  font-size: 14px; font-weight: 550; box-shadow: var(--shadow-2); z-index: 60;
}

`;

// Seeded content for Lumen.
//
// Everything the app shows comes from here, so a screenshot taken twice looks
// the same twice. No dates computed at load time, no shuffling, no random ids —
// a feed that reorders itself between two captures is unusable as footage.

const PEOPLE = [
  {h: 'maren.kova',   name: 'Maren Kovach',    av: 1,  bio: 'Light, water, and the odd rooftop.',           city: 'Lisbon',      follows: true  },
  {h: 'atlas.reads',  name: 'Atlas Ferreira',  av: 2,  bio: 'Film only. Mostly out of focus.',              city: 'São Paulo',   follows: true  },
  {h: 'noor.builds',  name: 'Noor Haddad',     av: 3,  bio: 'Concrete, glass, and long shadows.',           city: 'Amman',       follows: false },
  {h: 'juniper',      name: 'Juniper Wallace', av: 4,  bio: 'Plants I have not killed yet.',                city: 'Portland',    follows: true  },
  {h: 'kiro.wav',     name: 'Kiro Nakamura',   av: 5,  bio: 'Night walks. 35mm.',                           city: 'Osaka',       follows: false },
  {h: 'elsa.grn',     name: 'Elsa Grinde',     av: 6,  bio: 'Cold water swimmer. Warm coffee drinker.',     city: 'Bergen',      follows: true  },
  {h: 'tomas.p',      name: 'Tomás Prieto',    av: 7,  bio: 'Markets, mornings, motion blur.',              city: 'Mexico City', follows: false },
  {h: 'ada.frames',   name: 'Ada Okonkwo',     av: 8,  bio: 'Portraits of people mid-sentence.',            city: 'Lagos',       follows: true  },
  {h: 'wren',         name: 'Wren Adeyemi',    av: 9,  bio: 'Birds, buses, bad weather.',                   city: 'Bristol',     follows: false },
  {h: 'silje.o',      name: 'Silje Ødegård',   av: 10, bio: 'Two lenses, one bag.',                         city: 'Oslo',        follows: true  },
  {h: 'rafi.dev',     name: 'Rafi Chowdhury',  av: 11, bio: 'Rooftops at golden hour.',                     city: 'Dhaka',       follows: false },
  {h: 'mira.stills',  name: 'Mira Lindqvist',  av: 12, bio: 'Still life, moving city.',                     city: 'Helsinki',    follows: true  },
  {h: 'okan',         name: 'Okan Demir',      av: 13, bio: 'Ferries and fog.',                             city: 'Istanbul',    follows: false },
  {h: 'lune.mp4',     name: 'Lune Bertrand',   av: 14, bio: 'Shoots at 4am. Sleeps at 4pm.',                city: 'Marseille',   follows: false },
  {h: 'devi.k',       name: 'Devi Krishnan',   av: 15, bio: 'Colour first, subject second.',                city: 'Kochi',       follows: true  },
];

const ME = {h: 'sam.builds', name: 'Sam Ellery', av: 16, bio: 'Learning to build things.', city: 'Remote'};

const POSTS = [
  {id: 1,  by: 'maren.kova',  img: 1,  where: 'Alfama, Lisbon',       likes: 1284, when: '2h',
   text: 'Six flights up for this. Worth every one of them.', tags: ['rooftops', 'goldenhour'],
   comments: [['atlas.reads', 'the light on that wall'], ['elsa.grn', 'ok this is the one'], ['juniper', 'six flights is nothing, you are fine']]},
  {id: 2,  by: 'kiro.wav',    img: 2,  where: 'Dotonbori, Osaka',     likes: 3902, when: '4h',
   text: 'Rain makes better neon than neon does.', tags: ['35mm', 'night'],
   comments: [['lune.mp4', 'reflections are doing a lot of work here'], ['okan', 'what stock is this?']]},
  {id: 3,  by: 'juniper',     img: 3,  where: 'Portland, OR',         likes: 742,  when: '7h',
   text: 'Repotted everything. Two survivors, one casualty.', tags: ['plants'],
   comments: [['mira.stills', 'RIP to the third one'], ['maren.kova', 'the pot on the left though']]},
  {id: 4,  by: 'ada.frames',  img: 4,  where: 'Yaba, Lagos',          likes: 5610, when: '11h',
   text: 'He was telling me about his brother when I pressed the shutter. That is the whole photo.',
   tags: ['portrait'],
   comments: [['atlas.reads', 'mid-sentence is the only way'], ['silje.o', 'incredible'], ['devi.k', 'the hands!']]},
  {id: 5,  by: 'elsa.grn',    img: 5,  where: 'Bergen, Norway',       likes: 2211, when: '14h',
   text: 'Four degrees. In and out in ninety seconds.', tags: ['coldwater'],
   comments: [['wren', 'absolutely not'], ['juniper', 'ninety seconds too long']]},
  {id: 6,  by: 'atlas.reads', img: 6,  where: 'Vila Madalena',        likes: 1893, when: '18h',
   text: 'Expired roll from 2019. Shot it anyway.', tags: ['film', 'expired'],
   comments: [['kiro.wav', 'the colour shift is free grading'], ['mira.stills', 'love a gamble']]},
  {id: 7,  by: 'silje.o',     img: 7,  where: 'Grünerløkka, Oslo',    likes: 968,  when: '21h',
   text: 'Packed two lenses. Used one.', tags: ['streets'],
   comments: [['tomas.p', 'always the way']]},
  {id: 8,  by: 'devi.k',      img: 8,  where: 'Fort Kochi',           likes: 4127, when: '1d',
   text: 'Found the wall first. Waited for someone to walk past it.', tags: ['colour', 'patience'],
   comments: [['ada.frames', 'the wait is the craft'], ['noor.builds', 'that blue']]},
  {id: 9,  by: 'mira.stills', img: 9,  where: 'Kallio, Helsinki',     likes: 1355, when: '1d',
   text: 'Breakfast, arranged slightly too carefully.', tags: ['stilllife'],
   comments: [['elsa.grn', 'slightly?'], ['juniper', 'the napkin fold is sending me']]},
  {id: 10, by: 'tomas.p',     img: 10, where: 'Mercado de Jamaica',   likes: 2740, when: '1d',
   text: 'Flowers before six in the morning are a completely different colour.', tags: ['markets'],
   comments: [['devi.k', 'that is real'], ['rafi.dev', 'need to get up earlier']]},
  {id: 11, by: 'noor.builds', img: 11, where: 'Amman, Jordan',        likes: 1602, when: '2d',
   text: 'One building, four hours of shadow.', tags: ['architecture'],
   comments: [['silje.o', 'the diagonal is perfect']]},
  {id: 12, by: 'rafi.dev',    img: 12, where: 'Gulshan, Dhaka',       likes: 3318, when: '2d',
   text: 'The whole city goes warm for about eleven minutes.', tags: ['goldenhour', 'rooftops'],
   comments: [['maren.kova', 'eleven minutes is generous'], ['okan', 'chasing this next week']]},
];

// The grid on Explore uses everything, including the posts the feed does not show.
const EXPLORE = [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 1, 4, 8, 12, 2, 10];

const MY_POSTS = [20, 15, 22, 17, 13, 24, 19, 14, 21];

const THREADS = [
  {h: 'juniper',     last: 'sent you a photo',                 when: '12m', unread: true },
  {h: 'atlas.reads', last: 'ok but did you keep the negative?', when: '1h',  unread: true },
  {h: 'elsa.grn',    last: 'Saturday, 6am, no excuses',         when: '3h',  unread: false},
  {h: 'maren.kova',  last: 'You: on my way up now',             when: '1d',  unread: false},
  {h: 'devi.k',      last: 'Reacted 🔥 to your post',            when: '2d',  unread: false},
];

const MESSAGES = [
  {me: false, t: 'did you ever get that rooftop shot developed'},
  {me: true,  t: 'came back yesterday. one frame out of twelve is usable'},
  {me: false, t: 'thats a good ratio for expired film honestly'},
  {me: true,  t: 'posting the good one tonight'},
  {me: false, t: 'ok but did you keep the negative?'},
];

const NOTIFS = [
  {h: 'ada.frames',  t: 'liked your photo',            when: '4m'},
  {h: 'juniper',     t: 'started following you',        when: '22m'},
  {h: 'kiro.wav',    t: 'commented: "the grain here"',  when: '1h'},
  {h: 'elsa.grn',    t: 'liked your photo',            when: '3h'},
  {h: 'silje.o',     t: 'mentioned you in a comment',   when: '5h'},
];

const person = (h) => (h === ME.h ? ME : PEOPLE.find((p) => p.h === h));
const avatar = (h) => `${BASE}avatars/a${person(h).av}.jpg`;
const photo  = (n) => `${BASE}posts/p${n}.jpg`;


// Lumen — one page, five views, no build step.
//
// Views render into #view from the seeded data in data.js. State that a viewer
// can change (likes, follows, new comments, a posted photo) lives in `S` and is
// re-rendered from scratch, which is fine at this size and keeps every view a
// pure function of state.

/** Line icons at a single 1.7px stroke so a row of them reads as one set. */
function icon(name, size = 24) {
  const s = (d, extra = '') =>
    `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none"
      stroke="currentColor" stroke-width="1.7" stroke-linecap="round"
      stroke-linejoin="round">${d}${extra}</svg>`;
  switch (name) {
    case 'home':    return s('<path d="M3.2 10.9 12 4l8.8 6.9V20a1 1 0 0 1-1 1h-4.6v-6.3H8.8V21H4.2a1 1 0 0 1-1-1z"/>');
    case 'search':  return s('<circle cx="11" cy="11" r="7"/><path d="m16.3 16.3 4 4"/>');
    case 'compass': return s('<circle cx="12" cy="12" r="9"/><path d="m15.6 8.4-2.1 5.1-5.1 2.1 2.1-5.1z"/>');
    case 'plus':    return s('<rect x="3.5" y="3.5" width="17" height="17" rx="4.5"/><path d="M12 8.4v7.2M8.4 12h7.2"/>');
    case 'chat':    return s('<path d="M20.5 11.6c0 4.1-3.8 7.4-8.5 7.4a9.7 9.7 0 0 1-2.6-.35L5 20.5l1.2-3.3A7.1 7.1 0 0 1 3.5 11.6C3.5 7.5 7.3 4.2 12 4.2s8.5 3.3 8.5 7.4z"/>');
    case 'heart':   return s('<path d="M12 20.2s-7.6-4.6-7.6-9.4a4.3 4.3 0 0 1 7.6-2.7 4.3 4.3 0 0 1 7.6 2.7c0 4.8-7.6 9.4-7.6 9.4z"/>');
    case 'heartf':  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="currentColor"><path d="M12 20.6S3.9 15.7 3.9 10.6A4.7 4.7 0 0 1 12 7.5a4.7 4.7 0 0 1 8.1 3.1c0 5.1-8.1 10-8.1 10z"/></svg>`;
    case 'cmt':     return s('<path d="M20.5 11.8c0 4-3.8 7.2-8.5 7.2a9.9 9.9 0 0 1-2.6-.34L5 20.4l1.2-3.2A7 7 0 0 1 3.5 11.8C3.5 7.8 7.3 4.6 12 4.6s8.5 3.2 8.5 7.2z"/>');
    case 'share':   return s('<path d="M21 3.4 10.4 13.9M21 3.4l-6.8 17.3-3.8-7.8L2.7 9.2z"/>');
    case 'save':    return s('<path d="M6.5 3.6h11a1 1 0 0 1 1 1v15.6L12 16l-6.5 4.2V4.6a1 1 0 0 1 1-1z"/>');
    case 'savef':   return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="currentColor"><path d="M6.5 3.6h11a1 1 0 0 1 1 1v15.6L12 16l-6.5 4.2V4.6a1 1 0 0 1 1-1z"/></svg>`;
    case 'dots':    return s('<circle cx="5.5" cy="12" r="1.3" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.3" fill="currentColor" stroke="none"/><circle cx="18.5" cy="12" r="1.3" fill="currentColor" stroke="none"/>');
    case 'user':    return s('<circle cx="12" cy="8.6" r="3.9"/><path d="M4.6 20.4a7.6 7.6 0 0 1 14.8 0"/>');
    case 'grid':    return s('<rect x="3.6" y="3.6" width="6.2" height="6.2" rx="1.2"/><rect x="14.2" y="3.6" width="6.2" height="6.2" rx="1.2"/><rect x="3.6" y="14.2" width="6.2" height="6.2" rx="1.2"/><rect x="14.2" y="14.2" width="6.2" height="6.2" rx="1.2"/>');
    case 'tag':     return s('<path d="M20.4 13.1 13.1 20.4a1.6 1.6 0 0 1-2.3 0l-7.2-7.2V3.6h9.6l7.2 7.2a1.6 1.6 0 0 1 0 2.3z"/><circle cx="7.9" cy="7.9" r="1.4"/>');
    case 'img':     return s('<rect x="3.4" y="4.6" width="17.2" height="14.8" rx="2.6"/><circle cx="8.8" cy="10" r="1.6"/><path d="m3.9 17.4 4.6-4.3 4.1 3.6 3.1-2.7 4.8 4"/>', '');
    case 'mark':    return `<svg width="${size}" height="${size}" viewBox="0 0 28 28" fill="none"><circle cx="14" cy="14" r="12.2" stroke="#0D0F12" stroke-width="2.2"/><circle cx="14" cy="14" r="5.1" fill="#0D0F12"/><path d="M14 1.8v6.9M14 19.3v6.9M1.8 14h6.9M19.3 14h6.9" stroke="#0D0F12" stroke-width="2.2" stroke-linecap="round"/></svg>`;
    default: return '';
  }
}

const S = {
  view: 'home',
  likes: {},          // id -> bool
  saved: {},
  follows: {},        // handle -> bool
  extra: {},          // id -> [[handle, text]]
  open: null,         // post id shown in the lightbox
  tab: 'grid',
  chip: 'For you',
  thread: 'juniper',
  draft: null,        // {img, text, place, filter}
  posted: [],         // photo numbers posted this session, newest first
  toast: null,
};

const nfmt = (n) => n.toLocaleString('en-US');
const liked = (id) => (S.likes[id] ?? false);
const likeCount = (p) => p.likes + (liked(p.id) ? 1 : 0);
const following = (h) => (S.follows[h] ?? person(h).follows);

// ------------------------------------------------------------------ chrome

function sidebar() {
  const items = [
    ['home', 'Home', 'home'], ['explore', 'Explore', 'compass'],
    ['create', 'Create', 'plus'], ['messages', 'Messages', 'chat'],
    ['profile', 'Profile', 'user'],
  ];
  return `
  <aside class="side">
    <div class="brand">${icon('mark', 28)}<b>Lumen</b></div>
    <nav class="nav">
      ${items.map(([k, label, ic]) => `
        <button data-go="${k}" class="${S.view === k ? 'on' : ''}">
          ${icon(ic)}<span>${label}</span>
          ${k === 'messages' ? '<i class="dot"></i>' : ''}
        </button>`).join('')}
    </nav>
    <div class="spacer"></div>
    <button class="me-row">
      <img src="${avatar(ME.h)}" alt="">
      <span class="who"><b>${ME.name}</b><span>@${ME.h}</span></span>
    </button>
  </aside>`;
}

// ------------------------------------------------------------------ home

function storiesRow() {
  const seen = new Set(['tomas.p', 'wren', 'okan']);
  const who = ['maren.kova', 'kiro.wav', 'juniper', 'ada.frames', 'elsa.grn', 'atlas.reads'];
  return `<div class="stories">
    <div class="story mine">
      <div class="ring"><img src="${avatar(ME.h)}" alt=""><span class="plus">+</span></div>
      <span>Your story</span>
    </div>
    ${who.map((h) => `
      <div class="story ${seen.has(h) ? 'seen' : ''}">
        <div class="ring"><img src="${avatar(h)}" alt=""></div>
        <span>${h}</span>
      </div>`).join('')}
  </div>`;
}

function postCard(p, fresh) {
  const u = person(p.by);
  const cs = [...p.comments, ...(S.extra[p.id] ?? [])];
  const shown = cs.slice(-3);
  return `
  <article class="post ${fresh ? 'fresh' : ''}" data-post="${p.id}">
    <div class="post-top">
      <img class="av" src="${avatar(p.by)}" alt="">
      <span class="who"><b>${p.by}</b><span>${p.where}</span></span>
      <button class="more">${icon('dots', 20)}</button>
    </div>
    <div class="frame" data-open="${p.id}"><img src="${photo(p.img)}" alt=""></div>
    <div class="acts">
      <button data-like="${p.id}" class="${liked(p.id) ? 'liked' : ''}">${icon(liked(p.id) ? 'heartf' : 'heart')}</button>
      <button data-open="${p.id}">${icon('cmt')}</button>
      <button>${icon('share')}</button>
      <button class="save" data-save="${p.id}">${icon(S.saved[p.id] ? 'savef' : 'save')}</button>
    </div>
    <div class="post-body">
      <div class="likes">${nfmt(likeCount(p))} likes</div>
      <div class="cap"><b>${p.by}</b>${p.text}</div>
      ${p.tags?.length ? `<div class="tags">${p.tags.map((t) => `<span>#${t}</span>`).join('')}</div>` : ''}
      ${cs.length > 3 ? `<button class="more-c" data-open="${p.id}">View all ${cs.length} comments</button>` : ''}
      <div class="cmts">${shown.map(([h, t]) => `<div class="c"><b>${h}</b>${t}</div>`).join('')}</div>
      <div class="more-c" style="pointer-events:none">${p.when} ago</div>
    </div>
    <form class="add-c" data-cmt="${p.id}">
      <input placeholder="Add a comment…" autocomplete="off">
      <button class="send" type="submit">Post</button>
    </form>
  </article>`;
}

function homeView() {
  const mine = S.posted.map((n, i) => ({
    id: 900 + i, by: ME.h, img: n, where: 'Just now', likes: 0, when: 'now',
    text: S.draft?.text || 'First one from the new build.', tags: ['lumen'], comments: [],
  }));
  const feed = [...mine, ...POSTS];
  return `
  <div class="main">
    <div class="col">
      ${storiesRow()}
      ${feed.map((p, i) => postCard(p, i === 0 && mine.length > 0)).join('')}
    </div>
    <div class="rail">
      <div class="rail-card">
        <h3>Activity</h3>
        ${NOTIFS.map((n) => `
          <div class="notif">
            <img src="${avatar(n.h)}" alt="">
            <p><b>${n.h}</b> ${n.t} <em>· ${n.when}</em></p>
          </div>`).join('')}
      </div>
      <div class="rail-card">
        <h3>Suggested for you</h3>
        ${['noor.builds', 'kiro.wav', 'tomas.p', 'wren', 'lune.mp4'].map((h) => {
          const u = person(h), f = following(h);
          return `<div class="sug">
            <img src="${avatar(h)}" alt="">
            <span class="who"><b>${h}</b><span>${u.city}</span></span>
            <button class="btn-follow ${f ? 'yes' : 'no'}" data-follow="${h}">${f ? 'Following' : 'Follow'}</button>
          </div>`;
        }).join('')}
      </div>
      <div class="foot">Lumen · About · Help · Privacy<br>© 2026 Lumen</div>
    </div>
  </div>`;
}

// ------------------------------------------------------------------ explore

function exploreView() {
  const chips = ['For you', 'Portraits', 'Streets', 'Film', 'Architecture', 'Nature'];
  return `
  <div class="main">
    <div class="col" style="width:934px">
      <div class="head"><h1>Explore</h1><span class="sub">Updated 6 minutes ago</span></div>
      <div class="chips">${chips.map((c) => `<button class="chip ${S.chip === c ? 'on' : ''}" data-chip="${c}">${c}</button>`).join('')}</div>
      <div class="grid">
        ${EXPLORE.map((n, i) => {
          const p = POSTS.find((q) => q.img === n);
          const l = p ? likeCount(p) : 400 + n * 137;
          return `<div class="cell ${i === 4 || i === 12 ? 'tall' : ''}" ${p ? `data-open="${p.id}"` : ''}>
            <img src="${photo(n)}" alt="">
            <div class="veil">
              <span>${icon('heartf', 18)} ${nfmt(l)}</span>
              <span>${icon('cmt', 18)} ${p ? p.comments.length : (n % 7) + 2}</span>
            </div>
          </div>`;
        }).join('')}
      </div>
    </div>
  </div>`;
}

// ------------------------------------------------------------------ profile

function profileView() {
  const grid = [...S.posted, ...MY_POSTS];
  return `
  <div class="main">
    <div class="col" style="width:934px">
      <div class="prof">
        <img class="big" src="${avatar(ME.h)}" alt="">
        <div class="meta">
          <div class="row1">
            <h2>${ME.h}</h2>
            <button class="btn ghost">Edit profile</button>
            <button class="btn ghost">Share</button>
          </div>
          <div class="stats">
            <div><b>${grid.length}</b> posts</div>
            <div><b>2,418</b> followers</div>
            <div><b>312</b> following</div>
          </div>
          <div class="name">${ME.name}</div>
          <div class="bio">${ME.bio}<br>Building this app while learning how to build apps.</div>
        </div>
      </div>
      <div class="tabs">
        <button class="on">${icon('grid', 15)} Posts</button>
        <button>${icon('save', 15)} Saved</button>
        <button>${icon('tag', 15)} Tagged</button>
      </div>
      <div class="grid" style="margin-top:16px">
        ${grid.map((n, i) => `<div class="cell ${i === 0 && S.posted.length ? 'fresh' : ''}">
          <img src="${photo(n)}" alt="">
          <div class="veil"><span>${icon('heartf', 18)} ${nfmt(210 + n * 91)}</span><span>${icon('cmt', 18)} ${(n % 6) + 1}</span></div>
        </div>`).join('')}
      </div>
    </div>
  </div>`;
}

// ------------------------------------------------------------------ messages

function messagesView() {
  const t = person(S.thread);
  return `
  <div class="main">
    <div class="col" style="width:934px">
      <div class="head"><h1>Messages</h1><span class="sub">2 unread</span></div>
      <div class="dm">
        <div class="dm-list">
          ${THREADS.map((th) => `
            <button class="t ${S.thread === th.h ? 'on' : ''}" data-thread="${th.h}" style="width:100%;text-align:left">
              <img src="${avatar(th.h)}" alt="">
              <span class="who"><b>${th.h}</b><span>${th.last}</span></span>
              <span class="when">${th.when}</span>
            </button>`).join('')}
        </div>
        <div class="dm-pane">
          <div class="dm-head"><img src="${avatar(S.thread)}" alt=""><b>${S.thread}</b>
            <span style="margin-left:auto;color:var(--ink-3)">${icon('dots', 20)}</span></div>
          <div class="dm-body">
            ${MESSAGES.map((m) => `<div class="bub ${m.me ? 'me' : 'them'}">${m.t}</div>`).join('')}
          </div>
          <form class="dm-foot" data-dm="1">
            <input placeholder="Message ${S.thread}…" autocomplete="off">
          </form>
        </div>
      </div>
    </div>
  </div>`;
}

// ------------------------------------------------------------------ composer

const FILTERS = [
  ['None', 'none'],
  ['Ferrier', 'saturate(1.18) contrast(1.06)'],
  ['Bergen', 'grayscale(1) contrast(1.1)'],
  ['Kodachrome', 'saturate(1.4) hue-rotate(-8deg) contrast(1.08)'],
  ['Faded', 'saturate(.78) brightness(1.06) contrast(.94)'],
];

function createView() {
  const d = S.draft;
  const f = FILTERS.find(([n]) => n === (d?.filter ?? 'None'));
  return `
  <div class="main">
    <div class="col" style="width:934px">
      <div class="head"><h1>New post</h1><span class="sub">Step ${d ? 2 : 1} of 2</span></div>
      <div class="comp">
        <div class="stage">
          ${d
            ? `<img src="${photo(d.img)}" style="filter:${f[1]}" alt="">`
            : `<button class="drop" data-pick="1">${icon('img', 46)}<b>Drag a photo here</b><p>or click to choose one from your library</p></button>`}
        </div>
        <div class="panel">
          <div class="field">
            <label>Caption</label>
            <textarea rows="4" data-field="text" placeholder="Say something about it…">${d?.text ?? ''}</textarea>
          </div>
          <div class="field">
            <label>Location</label>
            <input type="text" data-field="place" value="${d?.place ?? ''}" placeholder="Add a place">
          </div>
          <div class="field">
            <label>Look</label>
            <div class="filters">
              ${FILTERS.map(([n, css]) => `
                <button class="f ${(d?.filter ?? 'None') === n ? 'on' : ''}" data-filter="${n}" ${d ? '' : 'disabled'}>
                  <span class="sw"><img src="${photo(d?.img ?? 6)}" style="filter:${css};opacity:${d ? 1 : .35}" alt=""></span>
                  <span>${n}</span>
                </button>`).join('')}
            </div>
          </div>
          <button class="go" data-share="1" ${d ? '' : 'disabled'}>Share</button>
        </div>
      </div>
    </div>
  </div>`;
}

// ------------------------------------------------------------------ lightbox

function lightbox() {
  const p = POSTS.find((q) => q.id === S.open);
  if (!p) return '';
  const cs = [...p.comments, ...(S.extra[p.id] ?? [])];
  return `
  <div class="lb" data-close="1">
    <button class="x" data-close="1">✕</button>
    <div class="sheet" data-stop="1">
      <div class="pic"><img src="${photo(p.img)}" alt=""></div>
      <div class="side-pane">
        <div class="post-top" style="border-bottom:1px solid var(--line)">
          <img class="av" src="${avatar(p.by)}" alt="">
          <span class="who"><b>${p.by}</b><span>${p.where}</span></span>
          <button class="more">${icon('dots', 20)}</button>
        </div>
        <div class="list">
          <div class="cmts" style="margin-top:14px">
            <div class="c"><b>${p.by}</b>${p.text}</div>
            ${cs.map(([h, t]) => `<div class="c"><b>${h}</b>${t}</div>`).join('')}
          </div>
        </div>
        <div class="acts" style="border-top:1px solid var(--line)">
          <button data-like="${p.id}" class="${liked(p.id) ? 'liked' : ''}">${icon(liked(p.id) ? 'heartf' : 'heart')}</button>
          <button>${icon('cmt')}</button><button>${icon('share')}</button>
          <button class="save" data-save="${p.id}">${icon(S.saved[p.id] ? 'savef' : 'save')}</button>
        </div>
        <div class="post-body" style="padding-top:0">
          <div class="likes">${nfmt(likeCount(p))} likes</div>
          <div class="more-c" style="pointer-events:none">${p.when} ago</div>
        </div>
        <form class="add-c" data-cmt="${p.id}">
          <input placeholder="Add a comment…" autocomplete="off">
          <button class="send" type="submit">Post</button>
        </form>
      </div>
    </div>
  </div>`;
}



// --------------------------------------------------------------- the film's seam

const DEFAULTS = JSON.parse(JSON.stringify(S));
const VIEWS = {home: homeView, explore: exploreView, profile: profileView,
               messages: messagesView, create: createView};

/** The whole page as markup, for one explicit state. Nothing is remembered
 *  between calls, so frame N never inherits frame N-1's likes. */
export function pageHTML(over = {}) {
  Object.assign(S, JSON.parse(JSON.stringify(DEFAULTS)), over);
  const body = (VIEWS[S.view] ?? homeView)();
  return sidebar() + body + (S.open ? lightbox() : '');
}

export {POSTS, PEOPLE, ME, EXPLORE, MY_POSTS, THREADS, MESSAGES, NOTIFS,
        person, avatar, photo, icon, nfmt};
