// Port the running app into a module the film can mount.
//
// The film does not screenshot Lumen. It mounts Lumen's real DOM inside the
// composition, which is the only way a camera push stays sharp — this machine's
// display caps a browser capture at ~1440x790, well under the 1920x1080 the
// film renders at, so any screenshot would have to be upscaled.
//
// Mounting the real thing also means the app is the single source of truth:
// edit demo/lumen and re-run this, and the footage changes with it.

import {readFileSync, writeFileSync} from 'fs';
import {dirname, join} from 'path';
import {fileURLToPath} from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const app = join(here, '..', '..', '..', 'demo', 'lumen');
const read = (p) => readFileSync(join(app, p), 'utf8');

let css = read('css/style.css');
if (css.includes('`') || css.includes('${')) throw new Error('CSS is not safe to embed raw');

// The film injects this stylesheet inside a <style> in the composition, and a
// <style> applies to the whole document wherever it sits. Unscoped, the app's
// resets would reach the film's own chrome: `* { margin: 0 }` would touch the
// kit's cards and `body { background: #FBFBFC }` would put a white sheet behind
// every frame, visible the instant anything failed to cover it. So the handful
// of element-level rules get scoped to .app on the way through.
// Every rewritten reset goes inside :where(), which contributes *zero*
// specificity. Scoping them the obvious way — `.app *` — silently broke the
// app's own spacing in the film: `.app *` scores (0,1,1) against `.head`'s
// (0,1,0), so the reset's `margin: 0` beat `.head { margin-bottom: 22px }` and
// `.col { padding: 30px 0 90px }`, and every screen shot lost ~50px of vertical
// rhythm. `.app button { background: none }` was likewise beating `.btn`, which
// would have rendered the Share button with no fill at all. Inside :where()
// they lose to everything, which is what a reset is supposed to do.
const scope = [
  ['html, body {', '.app {'],
  ['* { box-sizing: border-box; margin: 0; padding: 0; }',
   ':where(.app, .app *) { box-sizing: border-box; margin: 0; padding: 0; }'],
  ['button { font:', ':where(.app button) { font:'],
  ['img { display: block; }', ':where(.app img) { display: block; }'],
  ['a { color: inherit; text-decoration: none; }',
   ':where(.app a) { color: inherit; text-decoration: none; }'],
  ['::selection {', ':where(.app) ::selection {'],
];
for (const [from, to] of scope) {
  if (!css.includes(from)) throw new Error(`cannot scope, rule moved: ${from}`);
  css = css.replace(from, to);
}
css = css.replace('.app {\n  height: 100%;', '.app {\n  min-height: 100%;');

// Photo and avatar paths move from the dev server's ./img to Remotion's public/.
const rebase = (s) =>
  s.replace(/img\/avatars\//g, '${BASE}avatars/').replace(/img\/posts\//g, '${BASE}posts/');

const data = rebase(read('js/data.js'));

let logic = read('js/app.js');
const cut = logic.indexOf('// ------------------------------------------------------------------ render');
if (cut < 0) throw new Error('render marker not found in app.js');
logic = rebase(logic.slice(0, cut));

// Everything that only exists to serve a live page comes out: the unused icon
// stub, the DOM helper, and (below the marker) the event listeners.
logic = logic.replace(/^const I = \{[\s\S]*?\n\};\n\n/m, '');
logic = logic.replace(/^const el = .*\n/m, '');

const out = `// @ts-nocheck
// GENERATED by port-lumen.mjs — do not edit by hand.
// Source of truth: demo/lumen/{css/style.css,js/data.js,js/app.js}

export let BASE = '/lumen/';
export const setBase = (b) => { BASE = b; };

export const CSS = String.raw\`
${css}
\`;

${data}

${logic}

// --------------------------------------------------------------- the film's seam

const DEFAULTS = JSON.parse(JSON.stringify(S));
const VIEWS = {home: homeView, explore: exploreView, profile: profileView,
               messages: messagesView, create: createView};

/** The whole page as markup, for one explicit state. Nothing is remembered
 *  between calls, so frame N never inherits frame N-1's likes. */
export function pageHTML(over = {}) {
  Object.assign(S, JSON.parse(JSON.stringify(DEFAULTS)), over);
  const body = (VIEWS[S.view] ?? homeView)();
  return sidebar() + body + (S.open ? lightbox() : '');
}

export {POSTS, PEOPLE, ME, EXPLORE, MY_POSTS, THREADS, MESSAGES, NOTIFS,
        person, avatar, photo, icon, nfmt};
`;

const target = join(here, 'lumen.gen.ts');
writeFileSync(target, out);
console.error(`wrote ${target} (${(out.length / 1024).toFixed(1)} kB)`);
