/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{course}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRunStatus"];
        put?: never;
        post: operations["startRun"];
        delete: operations["cancelRun"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Server-sent events: run-started, stage-started, stage-finished, stage-failed, log, run-finished, run-failed, quota. Supports Last-Event-ID resume. */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["regenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz/{course}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuiz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz-overrides/{course}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putQuizOverrides"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List combos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description combos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComboSummary"][];
                    };
                };
            };
        };
        put?: never;
        /** Create and run a combo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComboSummary"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combos/direct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Direct a whole piece from a subject: outline it, cast the looks, propose the segments (writes nothing) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description proposal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DirectComboResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One combo with its segments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description combo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComboDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a combo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combos/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run a combo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combos/{id}/segments/{segment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit one segment */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description segments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComboSegmentInfo"][];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/snippet-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSnippetTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snippets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSnippets"];
        put?: never;
        post: operations["createSnippet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snippets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSnippet"];
        put?: never;
        post?: never;
        delete: operations["deleteSnippet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Course: {
            name: string;
            slug: string;
            description: string;
            lesson_count: number;
        };
        LessonSummary: {
            id: string;
            title: string;
            stages: {
                [key: string]: "done" | "stale" | "pending";
            };
        };
        CourseDetail: components["schemas"]["Course"] & {
            stage_order: string[];
            lessons: components["schemas"]["LessonSummary"][];
        };
        Artifact: {
            name: string;
            size: number;
            url: string;
            /** @description What this file should be saved as: <course>-<lesson>[-<part>].<ext>, so a folder of downloads sorts by course and lesson instead of being six copies of final.mp4. */
            download_name: string;
        };
        DirectComboResponse: {
            title: string;
            /** @description What the piece argues. POST it back with the proposal — it is what the critic scores every finished segment against, and a combo created without one gets a critic that can only ask whether a segment is good. */
            angle: string;
            /** @description Which catalog the chosen theme narrowed the casting to, in words. */
            pool?: string;
            /** @description How the requested runtime was spread over segments, and whether it could be met. */
            runtime?: string;
            segments: {
                template: string;
                /** @description What this segment establishes — the increment, not the topic. */
                prompt: string;
                heading?: string;
                /** @enum {string} */
                role?: "hook" | "develop" | "payoff";
                /** @description The director's reason for this look. */
                why?: string;
                /** @description The concrete facts this template will be filled with. POST it back with the proposal — a segment created without it is planned from the one-line prompt alone, and its writer invents the specifics. */
                material?: string;
                target_sec?: number;
            }[];
        };
        ComboSegmentInfo: {
            id: string;
            template: string;
            prompt: string;
            /** @description The concrete facts this segment is planned from. The field most worth correcting by hand: a wrong figure here becomes a wrong figure in the finished video. */
            material?: string;
            /** @description Which part of the argument this segment is. Empty on a hand-authored combo. */
            heading?: string;
            /**
             * @description This segment's job in the arc. Read-only: it tells you whether to rewrite a segment, where the material tells you what to correct.
             * @enum {string}
             */
            role?: "hook" | "develop" | "payoff";
            /** @description The director's reason for this look. */
            why?: string;
            target_sec?: number;
            skip?: boolean;
            template_title: string;
            template_category: string;
        };
        ComboSummary: {
            id: string;
            title: string;
            brief?: string;
            segments: number;
            skipped: number;
            ready: boolean;
            video_url?: string;
            created_at?: string;
            run_id?: string;
        };
        ComboDetail: components["schemas"]["ComboSummary"] & {
            segment_list: components["schemas"]["ComboSegmentInfo"][];
            plan?: unknown;
        };
        SnippetTemplateInfo: {
            name: string;
            title: string;
            description: string;
            example: string;
            shows_code: boolean;
            min_target_sec?: number;
            default_target_sec?: number;
            category: string;
            category_title: string;
            since?: string;
            family?: string;
            takes_narration?: boolean;
        };
        SnippetSummary: {
            id: string;
            title: string;
            prompt: string;
            template: string;
            ready: boolean;
            video_url?: string;
            created_at?: string;
        };
        SnippetDetail: components["schemas"]["SnippetSummary"] & {
            target_sec: number;
            plan?: unknown;
        };
        CreateSnippetRequest: {
            prompt: string;
            template: string;
            title?: string;
            narration?: string;
            target_sec?: number;
            code_language?: string;
            voice?: string;
            plan_only?: boolean;
            /** @enum {string} */
            captions?: "on" | "off";
            /** @enum {string} */
            mode?: "dark" | "light";
            /** @enum {string} */
            skin?: "default" | "broadcast" | "minimal" | "editorial" | "showroom";
        };
        CreateSnippetResponse: components["schemas"]["SnippetSummary"] & {
            run_id?: string;
        };
        LessonDetail: {
            course: string;
            id: string;
            title: string;
            source: string;
            stages: {
                [key: string]: string;
            };
            stage_order: string[];
            artifacts: components["schemas"]["Artifact"][];
            script?: components["schemas"]["Script"];
            quiz?: components["schemas"]["Quiz"];
            mistakes?: unknown;
            exercises?: unknown;
            chapters?: components["schemas"]["Chapter"][];
            alignment?: unknown;
            reviews?: {
                [key: string]: unknown;
            };
        };
        Script: {
            title: string;
            sections: {
                id: string;
                narration: string;
                duration_est_sec?: number;
                cues?: {
                    type?: string;
                    ref?: string;
                    at_word?: number;
                }[];
            }[];
        };
        Quiz: {
            title: string;
            questions: components["schemas"]["Question"][];
        };
        Question: {
            id: string;
            /** @enum {string} */
            type: "recall" | "application" | "debugging" | "prediction";
            prompt: string;
            review?: boolean;
            options: string[];
            answer_index: number;
            explanation: string;
        };
        QuizOverrides: {
            questions: {
                id: string;
                drop?: boolean;
                prompt?: string;
                options?: string[];
                answer_index?: number;
                explanation?: string;
            }[];
        };
        QuizWithOverrides: {
            generated?: components["schemas"]["Quiz"];
            overrides?: components["schemas"]["QuizOverrides"];
            merged?: components["schemas"]["Quiz"];
        };
        Chapter: {
            id: string;
            title: string;
            start_ms: number;
            end_ms: number;
        };
        RunRequest: {
            course: string;
            lesson: string;
            stage?: string;
            force?: boolean;
        };
        RunStatus: {
            running: boolean;
            run_id?: string;
            course?: string;
            lesson?: string;
            stage?: string;
        };
        Event: {
            /** @enum {string} */
            type: "run-started" | "stage-started" | "stage-finished" | "stage-skipped" | "stage-failed" | "log" | "run-finished" | "run-failed" | "quota";
            run_id?: string;
            course?: string;
            lesson?: string;
            stage?: string;
            line?: string;
            error?: string;
            seq: number;
            /** Format: date-time */
            at: string;
        };
        FeedbackRequest: {
            course: string;
            lesson: string;
            section?: string;
            note: string;
            timestamp_ms?: number;
        };
        RegenerateRequest: {
            course: string;
            lesson: string;
            /** @enum {string} */
            artifact: "script" | "quiz" | "visuals" | "mistakes" | "exercises" | "audio";
            section?: string;
            note?: string;
        };
        LedgerRow: {
            day: string;
            provider: string;
            model: string;
            calls: number;
            prompt_tokens: number;
            completion_tokens: number;
            cost_usd: number;
            /** @description False when this model is absent from the pricing table, which makes cost_usd meaningless rather than zero. Render it as unknown, never as $0.00 — the tokens were really spent. */
            priced: boolean;
        };
        QuotaStatus: {
            provider: string;
            per_minute: number;
            per_day: number;
            day_used: number;
        };
        Ledger: {
            rows: components["schemas"]["LedgerRow"][];
            total_cost_usd: number;
            total_calls: number;
            /** @description Models whose spend is missing from total_cost_usd, so the total is a floor rather than the bill. */
            unpriced_models?: string[];
            unpriced_tokens?: number;
            quotas: components["schemas"]["QuotaStatus"][];
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All parseable courses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"][];
                };
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course with lesson × stage matrix */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full lesson state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getRunStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Run accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run_id: string;
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canceling */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of Event objects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Event"];
                };
            };
        };
    };
    addFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Note saved to review-notes.yaml */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    regenerate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Forced regeneration started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run_id?: string;
                        stages?: string[];
                    };
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated quiz + overrides + merged result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizWithOverrides"];
                };
            };
        };
    };
    putQuizOverrides: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizOverrides"];
            };
        };
        responses: {
            /** @description Saved; returns overrides + merged quiz */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizWithOverrides"];
                };
            };
        };
    };
    getLedger: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token/cost/quota data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ledger"];
                };
            };
        };
    };
    listSnippetTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The visual template catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnippetTemplateInfo"][];
                };
            };
        };
    };
    listSnippets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every snippet, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnippetSummary"][];
                };
            };
        };
    };
    createSnippet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSnippetRequest"];
            };
        };
        responses: {
            /** @description Created; the pipeline is running */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSnippetResponse"];
                };
            };
            /** @description Created, but the pipeline was busy — re-run it later */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSnippetResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getSnippet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request plus the model's plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnippetDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteSnippet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
}
