// nocode09 — how a language model actually works (his L9, 11:02)
//
// His spine kept whole: the two warnings, autocomplete-on-steroids, tokens, the
// probability distribution, inference, model-versus-application, the four
// tricks, the illusion of memory, and reasoning with the two-coins demo.
//
// His version is slides only, start to finish, and it is the flattest lecture in
// Day 2. So this is where the new template library earns itself: `tokens` and
// `probs` for the distribution, `stepper` for inference, `chat` with a re-send
// flash for the memory illusion, `occupancy` and `gauge` for the window, `tree`
// for the coins, `myth` for the misconceptions, `nest` for model-vs-application.
//
// Ours are the X slides: hallucination as a direct consequence of "always the
// most likely next token" (X1-X4), why letter-counting fails (X5-X6), what
// training actually did and the cutoff (X7-X9), and three rules that fall out
// of it (X10). He asserts the mechanism and never cashes it out.

import React from 'react';
import {Deck, Slide, deckFrames, C} from './kit';

// adam_deck already bakes 0.22s of lead and 0.60s of tail into every clip, so a
// 0.12s gap still leaves ~0.94s of silence between slides. That is the beat.
export const DURS = [
  11.277, 12.709, 18.757, 11.756, 7.864, 13.282, 6.901, 14.321, 16.304,
  12.723, 16.912,
  10.112, 18.428,
  14.989, 18.313, 16.065, 17.462,
  13.081, 8.47, 18.104, 12.498, 9.277,
  6.056, 13.972, 14.947, 19.084,
  13.264, 15.04, 18.981, 19.065,
  11.107, 11.819, 7.361, 12.579, 12.891, 11.04, 13.265, 17.503,
  10.076, 12.8, 15.612,
  5.588, 13.953, 13.155, 12.455, 9.396, 14.002, 18.378, 13.301,
];
export const FILES = [
  '01', '02', '03', '04', '05', '06', '07', '08', '09',
  'X5', 'X6',
  '10', '11',
  'X1', 'X2', 'X3', 'X4',
  '12', '13', '14', '15', '16',
  '17', '18', '19', '20',
  'X7', 'X8', 'X9', 'X10',
  '21', '22', '23', '24', '25', '26', '27', '28',
  '29', '30', '31',
  '32', '33', '34', '35', '36', '37', '38', '39',
].map((n) => `${n}.mp3`);
export const GAP = 0.12;
export const L9_FRAMES = deckFrames(DURS, GAP);

const T = 'rise' as const;

const SLIDES: Slide[] = [
  {k: 'grid', kicker: 'day two', lines: ['You *survived*', 'day one'], done: 1, now: 1, trans: 'fade'},
  {k: 'rows', kicker: 'two warnings, and they are honest ones',
   lines: ['Today is *different*'], size: 74, trans: T,
   rows: [{t: 'It is mostly talking — almost nothing to install'},
          {t: 'And it is foundational, which sometimes means boring', hot: true}]},
  {k: 'rows', kicker: 'so here is the deal', lines: ['Skim it, or *skip* it'], size: 66, trans: T,
   rows: [{t: 'Already know how a model works? Put this on double speed'},
          {t: 'Nothing here is tested'},
          {t: 'But skip it and weeks two and three become magic that fails', hot: true}]},
  {k: 'rows', kicker: 'because this is the actual promise',
   lines: ['*Why*, not just what'], size: 70, trans: T,
   rows: [{t: 'An agent does something strange'},
          {t: 'You say: that is the context filling up'},
          {t: 'Instead of shrugging and trying again', hot: true}]},

  {k: 'head', kicker: 'one sentence, and it really is one',
   lines: ['It predicts what', 'comes *next*'], size: 78, trans: 'push'},
  {k: 'rows', kicker: 'that is genuinely all of it',
   lines: ['*Autocomplete*', 'on steroids'], size: 78, trans: T,
   rows: [{t: 'An enormous statistical pattern matcher'},
          {t: 'Trained on more text than you can picture'},
          {t: 'Doing one job: given this, what usually follows?', hot: true}]},
  {k: 'head', kicker: 'first correction, and it matters',
   lines: ['Not words.', '*Tokens*'], size: 92, trans: 'push'},
  {k: 'tokens', kicker: 'everything you type is chopped up first',
   lines: ['A fixed *vocabulary*', 'of chunks'], size: 58, trans: T,
   chips: ['Un', 'question', 'ably', ' the', ' capital', ' of', ' France'],
   hot: [0, 1, 2],
   caption: 'often a word, often part of one, sometimes a space and a letter'},
  {k: 'rows', kicker: 'and here is why that is worth knowing',
   lines: ['The chunks ignore', '*words*'], size: 66, trans: T,
   rows: [{t: 'A long or unusual word becomes pieces that mean nothing alone'},
          {t: 'So when it miscounts letters, that is not stupidity'},
          {t: 'It never saw the letters', hot: true}]},

  {k: 'head', kicker: 'one more consequence of tokens',
   lines: ['The *letter*', 'party trick'], size: 84, trans: T},
  {k: 'myth', kicker: 'people screenshot this as proof it is stupid', trans: 'push',
   lines: ['Counting *letters*'], size: 62,
   wrong: 'It cannot even count to three',
   right: 'It was never *shown* the letters',
   note: 'The word arrived as two or three chunks. The letters inside a chunk are no more visible to it than the pixels in a printed word are to you.'},

  {k: 'head', kicker: 'second correction, and this one changes everything',
   lines: ['It does not pick', 'a *word*'], size: 74, trans: 'push'},
  {k: 'probs', kicker: 'it scores every token it knows',
   lines: ['"Two plus two is ..."'], size: 62, trans: T,
   items: [{t: 'four', p: 94}, {t: 'lots', p: 3}, {t: '4', p: 2}, {t: 'bananas', p: 0.001}],
   caption: 'a probability for every single chunk in its vocabulary'},

  {k: 'rows', kicker: 'and that near-zero is worth pausing on',
   lines: ['There is no *zero*'], size: 78, trans: T,
   rows: [{t: 'Every token it knows has some probability, always'},
          {t: 'So there is always a path to a completely absurd answer', hot: true}]},
  {k: 'myth', kicker: 'which gives you the honest definition', trans: 'push',
   lines: ['*Hallucination*'], size: 74,
   wrong: 'The model malfunctioned',
   right: 'It did *exactly* its job',
   note: 'It produced the most plausible continuation. Plausible and true are different targets, and it was only ever aiming at one of them.'},
  {k: 'rows', kicker: 'so when it invents a function that does not exist',
   lines: ['A very good *guess*'], size: 72, trans: T,
   rows: [{t: 'It is not lying, and it is not broken'},
          {t: 'That name, in that library, is what usually follows code like yours'},
          {t: 'It is a very good guess. It is just wrong.', hot: true}]},
  {k: 'rows', kicker: 'which tells you exactly where to look',
   lines: ['Check the *details*'], size: 74, trans: T,
   rows: [{t: 'A plausible file path. A plausible flag. A plausible version'},
          {t: 'That is precisely where a text predictor invents'},
          {t: 'It is far better on the shape of code than on the specifics', hot: true}]},

  {k: 'rows', kicker: 'then something picks one',
   lines: ['Same question,', 'two *answers*'], size: 66, trans: T,
   rows: [{t: 'Usually the top one — sometimes a little randomly, on purpose'},
          {t: 'That is not unreliability. It is a dial, and somebody set it', hot: true}]},
  {k: 'head', kicker: 'put those two facts together',
   lines: ['One token at a time,', 'input *re-read* every step'], size: 54, trans: 'push'},
  {k: 'stepper', kicker: 'watch it happen', lines: ['"What is the capital', 'of France?"'],
   size: 54, trans: T, seed: 'What is the capital of France?',
   steps: [' The', ' capital', ' of', ' France', ' is', ' Paris', '.'],
   caption: 'every step re-read the question and everything it had already written'},
  {k: 'rows', kicker: 'and nothing carried over between them',
   lines: ['Nothing was', '*remembered*'], size: 72, trans: T,
   rows: [{t: 'There was nothing to remember with'},
          {t: 'It just got handed the whole thing again', hot: true}]},
  {k: 'head', kicker: 'and that process has a name',
   lines: ['*Inference*'], size: 128, trans: 'push',
   stamp: 'this is what you pay for'},

  {k: 'head', kicker: 'a distinction people get wrong constantly',
   lines: ['The model, and the', '*thing around it*'], size: 60, trans: 'push'},
  {k: 'nest', kicker: 'gpt is a model. chatgpt is an application',
   lines: ['Not the same *thing*'], size: 62, trans: T,
   outer: 'the application', inner: 'the model',
   ring: ['remembers your chat', 'searches the web', 'runs code and tools', 'the interface']},
  {k: 'rows', kicker: 'the model does one job',
   lines: ['The rest is', 'ordinary *software*'], size: 62, trans: T,
   rows: [{t: 'Memory, search, files, the nice interface'},
          {t: 'Written by engineers. Not magic.', hot: true}]},
  {k: 'rows', kicker: 'and the pattern is everywhere once you see it',
   lines: ['Same engine,', 'different *chassis*'], size: 62, trans: T,
   rows: [{t: 'The agent in the editor you used yesterday'},
          {t: 'The chat-to-learn feature in a language app'},
          {t: 'The assistants appearing inside company software this year', hot: true}]},

  {k: 'rows', kicker: 'so what did training actually do?',
   lines: ['No facts were', '*stored*'], size: 68, trans: 'push',
   rows: [{t: 'It did not put a copy of the internet in a lookup table'},
          {t: 'It adjusted an enormous number of weights'},
          {t: 'Until it got good at one task: predicting what comes next', hot: true}]},
  {k: 'rows', kicker: 'which is why it knows things',
   lines: ['Patterns, not', '*records*'], size: 70, trans: T,
   rows: [{t: 'There is no fact in there you could point at'},
          {t: 'There are patterns strong enough that the fact falls out'},
          {t: 'Usually that does not matter. When it does, it matters a lot.', hot: true}]},
  {k: 'rows', kicker: 'and it is why there is a cutoff',
   lines: ['Not forgotten —', '*never present*'], size: 58, trans: T,
   rows: [{t: 'Training happened at a moment. After it is simply absent'},
          {t: 'A confident description of a library released since'},
          {t: 'is a guess at what a plausible future looked like', hot: true}]},
  {k: 'rows', kicker: 'three rules fall straight out of all of this',
   lines: ['Worth more than', 'the *theory*'], size: 62, trans: T, numbered: true,
   rows: [{t: 'Give it the real thing — a pasted file beats a remembered one'},
          {t: 'Expect confident detail to be invented, and check it'},
          {t: 'When a chat gets long and strange, start a new one', hot: true}]},

  {k: 'head', kicker: 'so why does any of this look like thinking?',
   lines: ['*Four* tricks'], size: 116, trans: 'push'},
  {k: 'rows', kicker: 'that is the whole list',
   lines: ['Two now,', 'two *next*'], size: 80, trans: T, numbered: true,
   rows: [{t: 'The illusion of memory'},
          {t: 'Reasoning'},
          {t: 'Tools — next lecture'},
          {t: 'The loop — next lecture'}]},

  {k: 'head', kicker: 'trick one', lines: ['The *illusion*', 'of memory'], size: 86, trans: 'push'},
  {k: 'rows', kicker: 'and illusion is precise here, not cynical',
   lines: ['Completely', '*stateless*'], size: 84, trans: T,
   rows: [{t: 'Not your name. Not what you asked a minute ago'},
          {t: 'Not that you already said you are using Python'},
          {t: 'Every call is the first call it has ever had', hot: true}]},
  {k: 'rows', kicker: 'prove it to yourself in two minutes',
   lines: ['Two *separate* calls'], size: 74, trans: T,
   rows: [{t: 'Call one: "my name is Sam." It answers politely'},
          {t: 'Call two, genuinely fresh: "who am I?"'},
          {t: 'No idea — because there was never anything to forget', hot: true}]},
  {k: 'chat', kicker: 'so why does the chat window remember?',
   lines: ['The *application*', 'does the remembering'], size: 54, trans: T,
   turns: [{who: 'you', t: 'I am learning to code with agents'},
           {who: 'model', t: 'Great — where would you like to start?'},
           {who: 'you', t: 'What am I learning?'}],
   resend: 2,
   caption: 'every turn quietly re-sends the entire conversation, then your new line'},
  {k: 'rows', kicker: 'that is the whole trick',
   lines: ['There is no memory.', 'There is *re-sending*'], size: 52, trans: T,
   rows: [{t: 'It reads a transcript that gets longer every time you speak'},
          {t: 'And behaves as though it recalls what it is reading fresh', hot: true}]},
  {k: 'rows', kicker: 'and this is the most useful thing today',
   lines: ['What it *buys* you'], size: 74, trans: T,
   rows: [{t: 'Why a long conversation gets slower and more expensive'},
          {t: 'Why an agent forgets an instruction from an hour ago'},
          {t: 'Why starting a fresh chat sometimes fixes everything', hot: true}]},

  {k: 'head', kicker: 'it also explains the limit',
   lines: ['The *context*', 'window'], size: 92, trans: 'push'},
  {k: 'occupancy', kicker: 'a fixed set of places, all of it visible at once',
   lines: ['And it only ever', '*fills up*'], size: 58, trans: T,
   used: 72, legend: 'spoken for',
   caption: 'your instructions, your files, and every turn so far'},
  {k: 'gauge', kicker: 'and when it will not fit', lines: ['Something has to *go*'], size: 66,
   trans: T, pct: 124, limit: 78, label: 'this conversation', limitLabel: 'the window',
   caption: 'dropped, summarised, or the tool simply refuses — we spend tomorrow here'},

  {k: 'head', kicker: 'trick two', lines: ['*Reasoning*'], size: 128, trans: 'push'},
  {k: 'rows', kicker: 'it started as a trick found by accident',
   lines: ['"Think *step*', 'by step"'], size: 78, trans: T,
   rows: [{t: 'Ask a hard question, get an immediate and bad answer'},
          {t: 'Add four words to the end, and it gets better'},
          {t: 'Same model, same question — told to work before answering', hot: true}]},
  {k: 'rows', kicker: 'which makes sense once you remember how it works',
   lines: ['It reads its own', '*working*'], size: 60, trans: T,
   rows: [{t: 'Every token it writes goes back into its own input'},
          {t: 'So writing the working first means reading it before the answer'},
          {t: 'It gave itself better input', hot: true}]},
  {k: 'rows', kicker: 'and that worked well enough to train in',
   lines: ['A *reasoning*', 'model'], size: 84, trans: T,
   rows: [{t: 'It produces its working first, then the answer'},
          {t: 'The interface usually hides it behind a little arrow', hot: true}]},
  {k: 'head', kicker: 'the demonstration that convinced me',
   lines: ['Two coins.', 'One is *heads*.'], size: 74, trans: 'push',
   stamp: 'is the other tails?'},
  {k: 'tree', kicker: 'four equally likely outcomes',
   lines: ['Being told one is heads', 'only removes *one*'], size: 48, trans: T,
   leaves: [{t: 'HH', keep: true, note: 'other is heads'},
            {t: 'HT', keep: true, note: 'other is tails'},
            {t: 'TH', keep: true, note: 'other is tails'},
            {t: 'TT', keep: false, note: 'ruled out'}],
   caption: 'three remain — and in two of them the other coin is tails'},
  {k: 'rows', kicker: 'so the fast answer is wrong',
   lines: ['*Two thirds*,', 'not a half'], size: 76, trans: T,
   rows: [{t: 'Answering immediately gives you a half, confidently'},
          {t: 'Writing the outcomes out first gives you two thirds'},
          {t: 'Same engine — it just gave itself room to work', hot: true}]},
  {k: 'rows', kicker: 'so that is two of the four',
   lines: ['Next: *tools*,', 'and the *loop*'], size: 66, trans: 'push',
   rows: [{t: 'It remembers nothing, and is handed everything'},
          {t: 'And it does better when it writes before it answers'},
          {t: 'Two more tricks, and you have an agent', hot: true}]},
];

export const Nocode09: React.FC = () => (
  <Deck slides={SLIDES} durs={DURS} voDir="nocode09/vo" files={FILES} gap={GAP} />
);
