// nocode12 — mastering agents.md (his L12, 11:52)
//
// The practical companion to L11. His spine kept whole: the markdown primer,
// why markdown specifically, the file as expensive real estate, the nested
// hierarchy (the promise L11 defers to), the filenames, what belongs in a real
// file, his do-and-don't list almost line for line, the focus-on-positives
// rule, and the 2025-vs-2026 split ending in the confession.
//
// Two new templates carry this one. `hierarchy` animates the nested rule —
// the agent lands on a file deep in the tree and the agents files light up in
// collection order, so "inner overrides outer" is readable off a single frame.
// A static slide genuinely cannot do that, which is why he never quite lands
// it. `editor` puts a real file on screen with the discussed lines lit, so one
// file gets walked section by section instead of a slide per section — the
// "show a real file, not a picture of one" win, rendered rather than filmed.
//
// The X slides are ours: he never says how to check the agent actually read
// the thing (X1-X3 — ask it to summarise its own instructions back), what to
// keep out of it (X4-X5), or that a stale line is worse than a missing one
// (X6-X7). The A slides fill the gaps his runtime leaves: a worked nested
// example, how long the file should be, chat-versus-file, two more standards,
// and the loop by which a good file actually gets written.

import React from 'react';
import {Deck, Slide, deckFrames, C} from './kit';

export const DURS = [
  12.716, 9.426, 14.139, 12.593, 11.556, 13.391, 13.265, 13.663, 6.395,
  11.681, 13.701, 10.299, 13.976, 11.167, 14.158, 14.14, 13.883, 13.834,
  11.18, 13.485, 13.834, 15.315, 7.601, 14.797, 15.751, 13.918, 13.982,
  10.344, 15.724, 7.893, 12.839, 8.175, 11.939, 11.331, 11.912, 15.055,
  8.987, 11.598, 14.475, 12.527, 6.504, 13.474, 12.673, 15.069, 15.522,
  13.075, 13.838, 13.46, 14.943, 9.369, 16.501, 12.29, 16.507, 13.806,
  12.534, 14.538, 10.39,
];
export const FILES = [
  '01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
  '11', '12', '13', '14', 'A1', 'A2', '15', '16', '17', '18',
  '19', '20', '21', '22', 'A3', 'A4', '23', '24', '25', '26',
  '27', '28', '29', '30', 'A5', 'A6', '31', '32', '33', '34',
  'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'A7', 'A8', '35',
  '36', '37', '38', '39', '40', '41', '42',
].map((n) => `${n}.mp3`);
export const GAP = 0;
export const L12_FRAMES = deckFrames(DURS, GAP);

// the markdown primer, as a file rather than a bullet list about files
const PRIMER = [
  {t: '# A big heading', kind: 'h1' as const},
  {t: '## A smaller one', kind: 'h2' as const},
  {t: '### Smaller still', kind: 'h2' as const},
  {t: '', kind: 'text' as const},
  {t: '- a bullet', kind: 'bullet' as const},
  {t: '- another bullet', kind: 'bullet' as const},
  {t: '1. a numbered item', kind: 'bullet' as const},
  {t: '2. and the next one', kind: 'bullet' as const},
  {t: '', kind: 'text' as const},
  {t: 'Wrap `code` in single backticks.', kind: 'text' as const},
  {t: '```', kind: 'code' as const},
  {t: 'uv run pytest', kind: 'code' as const},
  {t: '```', kind: 'code' as const},
];

// a real file, split into two views so neither one overflows the frame
const FILE_TOP = [
  {t: '# Kanban — agent instructions', kind: 'h1' as const},
  {t: '', kind: 'text' as const},
  {t: '## What this is', kind: 'h2' as const},
  {t: 'A small kanban board. FastAPI back end,', kind: 'text' as const},
  {t: 'React front end, Postgres in Docker.', kind: 'text' as const},
  {t: '', kind: 'text' as const},
  {t: '## Done means', kind: 'h2' as const},
  {t: '- Tests pass with `uv run pytest`', kind: 'bullet' as const},
  {t: '- Types check with `uv run mypy .`', kind: 'bullet' as const},
  {t: '- No file is left half-migrated', kind: 'bullet' as const},
  {t: '', kind: 'text' as const},
  {t: '## Before you call a task complete', kind: 'h2' as const},
  {t: '1. Run the tests', kind: 'bullet' as const},
  {t: '2. Run the type checker', kind: 'bullet' as const},
  {t: '3. Re-read this checklist', kind: 'bullet' as const},
  {t: '', kind: 'text' as const},
  {t: '## Detail — load only if you need it', kind: 'h2' as const},
  {t: '- Schema: `docs/schema.md`', kind: 'bullet' as const},
  {t: '- API contract: `docs/api.md`', kind: 'bullet' as const},
];
const FILE_STD = [
  {t: '## Standards', kind: 'h2' as const},
  {t: '- Simpler is better. Always.', kind: 'bullet' as const},
  {t: '- Comments only where necessary', kind: 'bullet' as const},
  {t: '- Keep readmes short', kind: 'bullet' as const},
  {t: '- No emojis, anywhere', kind: 'bullet' as const},
  {t: '- Let errors fail loudly', kind: 'bullet' as const},
  {t: '- Prefer the type system to runtime checks', kind: 'bullet' as const},
  {t: '- Use `uv run`, never `python3`', kind: 'bullet' as const},
  {t: '- Add to an existing file before making a new one', kind: 'bullet' as const},
  {t: '- Tried twice and still failing? Stop and explain', kind: 'bullet' as const},
  {t: '- IMPORTANT: never hand-edit a migration', kind: 'important' as const},
];

const TREE = [
  {t: 'kanban', depth: 0, kind: 'dir' as const},
  {t: 'agents.md', depth: 1, kind: 'agents' as const},
  {t: 'src', depth: 1, kind: 'dir' as const},
  {t: 'api', depth: 2, kind: 'dir' as const},
  {t: 'agents.md', depth: 3, kind: 'agents' as const},
  {t: 'routes.py', depth: 3, kind: 'file' as const},
  {t: 'db', depth: 2, kind: 'dir' as const},
  {t: 'agents.md', depth: 3, kind: 'agents' as const},
  {t: 'models.py', depth: 3, kind: 'file' as const},
];

const SLIDES: Slide[] = [
  // -------------------------------------------------------- markdown, briskly
  {k: 'head', kicker: 'the practical companion to last time',
   lines: ['The one file', 'you *write*'], size: 104, trans: 'fade',
   stamp: 'vague advice about this file is worse than none'},
  {k: 'head', kicker: 'and nobody wants to admit they need this bit',
   lines: ['Ten seconds', 'on *markdown*'], size: 92, trans: 'push'},
  {k: 'editor', kicker: 'the whole syntax you need', trans: 'rise',
   lines: ['Hashes and *hyphens*'], size: 58, file: 'example.md',
   rows: PRIMER, focus: [0, 7],
   caption: 'one hash is a big heading, three is a small one, a hyphen is a bullet'},
  {k: 'editor', kicker: 'and one more', trans: 'none',
   lines: ['Backticks for *code*'], size: 58, file: 'example.md',
   rows: PRIMER, focus: [9, 12],
   caption: 'one either side for a word, three on their own line for a block'},
  {k: 'head', kicker: 'which raises the obvious question',
   lines: ['Why *that*,', 'specifically?'], size: 98, trans: 'push'},
  {k: 'rows', kicker: 'because of what these models read growing up', trans: 'rise',
   lines: ['The training data', 'is *full* of it'], size: 58,
   rows: [{t: 'Documentation, readmes, wikis, forum posts'},
          {t: 'They read it comfortably and write it fluently'},
          {t: 'And the structure survives the trip into the context', hot: true}]},
  {k: 'head', kicker: 'so write it, and write it well',
   lines: ['High *signal*', 'per word'], size: 116, trans: 'fade',
   stamp: 'concise · crisp · assertive · low ambiguity'},
  {k: 'stack', kicker: 'because remember where this file ends up', trans: 'rise',
   lines: ['Expensive', '*real estate*'], size: 66,
   layers: [{t: 'System prompt', sub: 'role, job, tone', h: 1.1},
            {t: 'Tool descriptions', sub: 'every tool, described in words', h: 1.2},
            {t: 'Memory', sub: 'carried between conversations', h: 1.0},
            {t: 'agents.md', sub: 'the one row you write', h: 1.2, tone: C.blue},
            {t: 'The conversation so far', sub: 'and it only grows', h: 4.4}],
   hot: [3], foot: 'every single word in it is costing you something'},

  // ------------------------------------------------- the hierarchy, animated
  {k: 'head', kicker: 'and now the part I promised you last time',
   lines: ['“More complicated', 'than one *row*”'], size: 84, trans: 'push'},
  {k: 'hierarchy', kicker: 'the one everybody knows about', trans: 'fade',
   lines: ['One in the *root*'], size: 60, nodes: TREE, collect: [1],
   caption: 'read on every call, for every file in the project'},
  {k: 'hierarchy', kicker: 'but you can nest them, at any depth', trans: 'none',
   lines: ['Only read when it', 'works *in there*'], size: 56,
   nodes: TREE, active: 5, collect: [4],
   caption: 'so your deep database rules cost nothing on a front-end day'},
  {k: 'hierarchy', kicker: 'and it does not stop at the nearest one', trans: 'none',
   lines: ['It walks *outwards*', 'to the root'], size: 56,
   nodes: TREE, active: 5, collect: [4, 1], step: 0.8,
   caption: 'collecting every agents file on the way up, and reading the lot'},
  {k: 'head', kicker: 'which gives you the rule that matters',
   lines: ['*Inner* overrides', 'outer'], size: 104, trans: 'push',
   stamp: 'a specific rule that beats a general one'},
  {k: 'myth', kicker: 'and almost nobody uses it', trans: 'rise',
   lines: ['Most projects get', 'this *backwards*'], size: 58,
   wrong: 'one enormous root file covering every case',
   right: 'a short root file and three small specific ones',
   note: 'the long one is not more thorough — it is diluted'},
  {k: 'hierarchy', kicker: 'what that looks like on a real project', trans: 'fade',
   lines: ['Three small files,', 'not one *long* one'], size: 54,
   nodes: [{t: 'shop', depth: 0, kind: 'dir'},
           {t: 'agents.md', depth: 1, kind: 'agents'},
           {t: 'web', depth: 1, kind: 'dir'},
           {t: 'agents.md', depth: 2, kind: 'agents'},
           {t: 'api', depth: 1, kind: 'dir'},
           {t: 'agents.md', depth: 2, kind: 'agents'}],
   collect: [1, 3, 5], step: 0.7,
   caption: 'what it is and how to test · the component library · how migrations work'},
  {k: 'editor', kicker: 'and the inner one may contradict the outer one', trans: 'rise',
   lines: ['The *exception*', 'just works'], size: 58, file: 'web/agents.md',
   rows: [{t: '# Front end', kind: 'h1'},
          {t: '', kind: 'text'},
          {t: '- Components from `@shop/ui`, never raw HTML', kind: 'bullet'},
          {t: '- State lives in the route loader, not in hooks', kind: 'bullet'},
          {t: '', kind: 'text'},
          {t: '## Overrides', kind: 'h2'},
          {t: '- Ignore the 30-line rule here. Page components', kind: 'bullet'},
          {t: '  are long, and splitting them makes it worse.', kind: 'bullet'}],
   focus: [5, 7],
   caption: 'and it costs nothing anywhere else in the project'},

  // ------------------------------------------------------------- the filename
  {k: 'cols', kicker: 'on what to call it', trans: 'fade',
   lines: ['Three names,', 'one *idea*'], size: 58,
   cols: [{head: 'agents.md', items: ['Cursor', 'Codex', 'Copilot']},
          {head: 'claude.md', items: ['Claude Code']},
          {head: 'gemini.md', items: ['Antigravity']}]},
  {k: 'head', kicker: 'and the trend is real',
   lines: ['Write *agents.md*'], size: 116, trans: 'push',
   stamp: 'then a one-line file pointing at it for the others'},

  // ----------------------------------------------- what actually goes in one
  {k: 'head', kicker: 'so let me show you one rather than describe it',
   lines: ['It is all in the', '*specifics*'], size: 88, trans: 'fade'},
  {k: 'editor', kicker: 'top of the file', trans: 'rise',
   lines: ['Goals, and what', '*done* means'], size: 56, file: 'agents.md',
   rows: FILE_TOP, focus: [2, 9],
   caption: 'if it does not know what finished looks like, it will decide for you'},
  {k: 'editor', kicker: 'the highest-value block in the file', trans: 'none',
   lines: ['A checklist it has', 'to *tick off*'], size: 56, file: 'agents.md',
   rows: FILE_TOP, focus: [11, 14],
   caption: 'an actual list, not a hope'},
  {k: 'editor', kicker: 'and this one saves you real money', trans: 'none',
   lines: ['*Links*, not', 'contents'], size: 60, file: 'agents.md',
   rows: FILE_TOP, focus: [16, 18],
   caption: 'a path is a few tokens. the schema pasted in is a few thousand, every turn'},
  {k: 'editor', kicker: 'and then the section that earns its keep', trans: 'fade',
   lines: ['*Standards*'], size: 74, file: 'agents.md', start: 20,
   rows: FILE_STD, focus: [0, 0]},
  {k: 'head', kicker: 'and here is the principle behind all of it',
   lines: ['Every line is a', '*correction*'], size: 84, trans: 'push',
   stamp: 'not best practice you read — things it actually did to you'},
  {k: 'head', kicker: 'a question nobody seems to answer',
   lines: ['Under a *hundred*', 'lines'], size: 96, trans: 'fade',
   stamp: 'three hundred is not thorough, it is diluted'},
  {k: 'myth', kicker: 'and the related one', trans: 'rise',
   lines: ['File, or just *say it*?'], size: 60,
   wrong: 'I will mention it again if it comes up',
   right: 'would you have to say it again tomorrow?',
   note: 'if yes, it goes in the file. if it is only true today, say it and let it go'},

  // ------------------------------------------------ the standards, one by one
  {k: 'editor', kicker: 'steal all of these', trans: 'rise',
   lines: ['Agents *overcomplicate*', 'everything'], size: 50,
   file: 'agents.md', start: 20, rows: FILE_STD, focus: [1, 1],
   caption: 'given the slightest opportunity — so this line goes near the top'},
  {k: 'editor', kicker: 'left alone it narrates every line back to you', trans: 'none',
   lines: ['Comments only where', 'they are *necessary*'], size: 52,
   file: 'agents.md', start: 20, rows: FILE_STD, focus: [2, 2],
   caption: 'noise is not free — it costs context'},
  {k: 'head', kicker: 'four files, three badges, a contributing section',
   lines: ['Machine-written', 'readmes are the *worst*'], size: 74, trans: 'push',
   stamp: 'say "keep readmes short" and mean it'},
  {k: 'editor', kicker: 'headings, commit messages, log output', trans: 'fade',
   lines: ['No *emojis*.', 'Anywhere'], size: 66,
   file: 'agents.md', start: 20, rows: FILE_STD, focus: [4, 4],
   caption: 'say it once, in the file, and it stops'},
  {k: 'myth', kicker: 'it loves a try block with no plan behind it', trans: 'rise',
   lines: ['Let it *fail* loudly'], size: 62,
   wrong: 'wrap it, catch it, swallow it, carry on',
   right: 'handle what you can act on, let the rest raise',
   note: 'a swallowed exception is a bug you will find three weeks later'},
  {k: 'editor', kicker: 'it will scatter runtime checks through typed code',
   lines: ['Trust your *type system*'], size: 56, trans: 'none',
   file: 'agents.md', start: 20, rows: FILE_STD, focus: [6, 6]},
  {k: 'term', kicker: 'and be specific about your tooling', trans: 'rise',
   lines: ['Name the *command*'], size: 62, title: 'kanban', prompt: '',
   term: [{t: '# what it reaches for on its own', kind: 'out'},
          {t: '$ python3 -m pytest', kind: 'warn'},
          {t: '# what your project actually uses', kind: 'out'},
          {t: '$ uv run pytest', kind: 'ok'},
          {t: 'say which one, and say it is the only one', kind: 'out'}]},
  {k: 'head', kicker: 'and one that should not work, but does',
   lines: ['*IMPORTANT*', 'in block capitals'], size: 88, trans: 'push',
   stamp: 'it genuinely raises the weight on that line', stampColor: C.red},
  {k: 'editor', kicker: 'two more from experience', trans: 'fade',
   lines: ['Reuse the file', 'that *exists*'], size: 58,
   file: 'agents.md', start: 20, rows: FILE_STD, focus: [8, 8],
   caption: 'left alone it scatters helpers across four new modules'},
  {k: 'editor', kicker: 'and tell it what to do when it is stuck', trans: 'none',
   lines: ['Two tries, then', '*stop and explain*'], size: 54,
   file: 'agents.md', start: 20, rows: FILE_STD, focus: [9, 9],
   caption: 'without this line it keeps going, and the third approach is the worst one'},

  // ------------------------------------------------- the counterintuitive rule
  {k: 'head', kicker: 'now the one people get wrong most often',
   lines: ['Write what it', '*should* do'], size: 94, trans: 'push'},
  {k: 'flow', kicker: 'because of where the words end up', trans: 'rise',
   lines: ['“Never use *X*”', 'puts X in the context'], size: 52,
   nodes: [{t: 'you write it', sub: 'once, in the file'},
           {t: 'it is read', sub: 'on every single call'},
           {t: 'X is now in there', sub: 'forty times today', tone: C.red}],
   caption: 'models are oddly incoherent at remembering what to avoid'},
  {k: 'cols', kicker: 'same rule, far better behaviour', trans: 'fade',
   lines: ['So *invert* it'], size: 66,
   cols: [{head: 'instead of', items: ['do not write long functions',
                                        'never leave dead code',
                                        'do not add dependencies']},
          {head: 'write', items: ['keep functions under 30 lines',
                                   'delete what you replace',
                                   'use what is already installed']}]},
  {k: 'head', kicker: 'and in the spirit of honesty',
   lines: ['My own file breaks', 'this in *three places*'], size: 72, trans: 'push',
   stamp: 'nobody writes a perfect one — you edit it for the life of the project'},

  // ----------------------------------------- ours: test it, trim it, prune it
  {k: 'head', kicker: 'three things nobody tells you',
   lines: ['Before we leave', 'the *file*'], size: 92, trans: 'fade'},
  {k: 'term', kicker: 'one — how do you know it read it?', trans: 'rise',
   lines: ['*Ask* it'], size: 82, title: 'a fresh session', prompt: '',
   term: [{t: '> summarise the instructions you are working', kind: 'cmd'},
          {t: '  under, in your own words', kind: 'cmd'},
          {t: 'I should keep things simple, run tests with', kind: 'out'},
          {t: 'uv, avoid emojis, and stop after two failed', kind: 'out'},
          {t: 'attempts rather than trying a third approach.', kind: 'out'},
          {t: 'that is your file, read back to you', kind: 'ok'}]},
  {k: 'head', kicker: 'once when you write it, once a month after',
   lines: ['Twenty seconds.', 'Two *failure modes*'], size: 72, trans: 'push',
   stamp: 'not read at all — or read and understood differently'},
  {k: 'rows', kicker: 'two — what to keep out', trans: 'rise',
   lines: ['No *secrets*. Ever'], size: 74,
   rows: [{t: 'No API keys, no connection strings, no internal URLs'},
          {t: 'This file goes into a context window'},
          {t: 'And it goes into your repository', hot: true}]},
  {k: 'rows', kicker: 'and nothing that changes daily', trans: 'rise',
   lines: ['Today does not', 'belong in a *file*'], size: 60,
   rows: [{t: 'The current sprint, who is working on what'},
          {t: 'The bug you are fixing this afternoon'},
          {t: 'Say those in the conversation, and let them go', hot: true}]},
  {k: 'head', kicker: 'three, and it is the one that decides the file',
   lines: ['A stale line is worse', 'than a *missing* one'], size: 68, trans: 'push',
   stamp: 'missing makes it guess. stale makes it confidently wrong'},
  {k: 'rows', kicker: 'so prune it, deliberately', trans: 'rise',
   lines: ['It should *shrink*', 'as often as it grows'], size: 58,
   rows: [{t: 'A rule stops being true — delete it that day'},
          {t: 'You fix the root cause — delete the workaround line'},
          {t: 'If yours only ever grows, it is drifting', hot: true}]},
  {k: 'head', kicker: 'and one habit that writes the file for you',
   lines: ['Turn the *irritation*', 'into a line'], size: 74, trans: 'fade'},
  {k: 'flow', kicker: 'this is the actual loop', trans: 'rise',
   lines: ['Nobody writes a great', 'one from *nothing*'], size: 54,
   nodes: [{t: 'a rough file', sub: 'ten minutes, no more'},
           {t: 'it annoys you', sub: 'and it will'},
           {t: 'one more line', sub: 'thirty seconds', tone: C.yellow}],
   loop: true,
   caption: 'you do not author it. you accumulate it — a fortnight in, it is excellent'},

  // -------------------------------------------------- 2025, 2026, and the gap
  {k: 'head', kicker: 'which brings us to a real disagreement',
   lines: ['Two *schools*', 'of thought'], size: 100, trans: 'push'},
  {k: 'rows', kicker: 'the 2025 school', trans: 'rise',
   lines: ['Your results come from', '*sweating* this file'], size: 54,
   rows: [{t: 'One in the root, more in the subdirectories'},
          {t: 'Planning documents and explicit success criteria'},
          {t: 'Continually pruned and rewritten as you go'},
          {t: 'Stopped and restarted with fresh context when it drifts', hot: true}]},
  {k: 'head', kicker: 'and it is a real chunk of your day',
   lines: ['It was also', 'unambiguously *the way*'], size: 74, trans: 'push',
   stamp: 'the people doing it got far more out of these tools'},
  {k: 'rows', kicker: 'the 2026 mindset, which is close to the opposite', trans: 'fade',
   lines: ['Give up the *reins*'], size: 74,
   rows: [{t: 'Focus on the end goal rather than the route to it'},
          {t: 'Skills, loops, sub-agents, swarms'},
          {t: 'Let the system catch its own mistakes', hot: true}]},
  {k: 'head', kicker: 'and I will be straight about where I sit',
   lines: ['Still largely the', '*2025* school'], size: 88, trans: 'push',
   stamp: 'toy projects I let go. anything I care about, I am all over it'},
  {k: 'head', kicker: 'and that is going to look old-fashioned',
   lines: ['The field is moving', 'faster than *I am*'], size: 74, trans: 'fade'},
  {k: 'rows', kicker: 'so here is what to do with all of that', trans: 'rise',
   lines: ['Learn it *now*,', 'use less of it later'], size: 58,
   rows: [{t: 'It costs you an afternoon'},
          {t: 'And it makes everything in weeks two and three work better'},
          {t: 'Then you will know exactly which parts to stop writing', hot: true}]},
  {k: 'head', kicker: 'next — the workflows this file sits inside',
   lines: ['From *micromanaging*', 'to loops overnight'], size: 74, trans: 'push'},
];

export const Nocode12: React.FC = () => (
  <Deck slides={SLIDES} durs={DURS} voDir="nocode12/vo" files={FILES} gap={GAP} />
);
