package pipeline

// Country names the world map can draw, generated from the world-atlas
// countries-110m TopoJSON that renderer/src/components/geo.ts renders.
//
// Go needs the list because Go validates the plan: a country the map cannot
// find is a country that silently does not appear, which is the same class of
// failure as an icon name the renderer does not map — invisible until someone
// watches the clip. A drift test regenerates this comparison against the real
// TopoJSON, so a world-atlas upgrade that renames a country fails the suite.
//
// Antarctica is deliberately absent: geo.ts does not draw it, so accepting it
// here would validate a plan whose country never appears — the exact drift
// these lists exist to prevent. TestCountryVocabularyMatchesAtlas knows about
// that one omission and fails on any other.
//
// Regenerate from the atlas with:
//
//	node -e "const t=require('./renderer/node_modules/world-atlas/countries-110m.json');
//	  t.objects.countries.geometries.map(g=>g.properties.name).sort()
//	   .forEach(n=>console.log('\\t'+JSON.stringify(n)+': true,'))"

var mapCountryVocab = map[string]bool{
	"Afghanistan":              true,
	"Albania":                  true,
	"Algeria":                  true,
	"Angola":                   true,
	"Argentina":                true,
	"Armenia":                  true,
	"Australia":                true,
	"Austria":                  true,
	"Azerbaijan":               true,
	"Bahamas":                  true,
	"Bangladesh":               true,
	"Belarus":                  true,
	"Belgium":                  true,
	"Belize":                   true,
	"Benin":                    true,
	"Bhutan":                   true,
	"Bolivia":                  true,
	"Bosnia and Herz.":         true,
	"Botswana":                 true,
	"Brazil":                   true,
	"Brunei":                   true,
	"Bulgaria":                 true,
	"Burkina Faso":             true,
	"Burundi":                  true,
	"Cambodia":                 true,
	"Cameroon":                 true,
	"Canada":                   true,
	"Central African Rep.":     true,
	"Chad":                     true,
	"Chile":                    true,
	"China":                    true,
	"Colombia":                 true,
	"Congo":                    true,
	"Costa Rica":               true,
	"Croatia":                  true,
	"Cuba":                     true,
	"Cyprus":                   true,
	"Czechia":                  true,
	"Côte d'Ivoire":            true,
	"Dem. Rep. Congo":          true,
	"Denmark":                  true,
	"Djibouti":                 true,
	"Dominican Rep.":           true,
	"Ecuador":                  true,
	"Egypt":                    true,
	"El Salvador":              true,
	"Eq. Guinea":               true,
	"Eritrea":                  true,
	"Estonia":                  true,
	"Ethiopia":                 true,
	"Falkland Is.":             true,
	"Fiji":                     true,
	"Finland":                  true,
	"Fr. S. Antarctic Lands":   true,
	"France":                   true,
	"Gabon":                    true,
	"Gambia":                   true,
	"Georgia":                  true,
	"Germany":                  true,
	"Ghana":                    true,
	"Greece":                   true,
	"Greenland":                true,
	"Guatemala":                true,
	"Guinea":                   true,
	"Guinea-Bissau":            true,
	"Guyana":                   true,
	"Haiti":                    true,
	"Honduras":                 true,
	"Hungary":                  true,
	"Iceland":                  true,
	"India":                    true,
	"Indonesia":                true,
	"Iran":                     true,
	"Iraq":                     true,
	"Ireland":                  true,
	"Israel":                   true,
	"Italy":                    true,
	"Jamaica":                  true,
	"Japan":                    true,
	"Jordan":                   true,
	"Kazakhstan":               true,
	"Kenya":                    true,
	"Kosovo":                   true,
	"Kuwait":                   true,
	"Kyrgyzstan":               true,
	"Laos":                     true,
	"Latvia":                   true,
	"Lebanon":                  true,
	"Lesotho":                  true,
	"Liberia":                  true,
	"Libya":                    true,
	"Lithuania":                true,
	"Luxembourg":               true,
	"Macedonia":                true,
	"Madagascar":               true,
	"Malawi":                   true,
	"Malaysia":                 true,
	"Mali":                     true,
	"Mauritania":               true,
	"Mexico":                   true,
	"Moldova":                  true,
	"Mongolia":                 true,
	"Montenegro":               true,
	"Morocco":                  true,
	"Mozambique":               true,
	"Myanmar":                  true,
	"N. Cyprus":                true,
	"Namibia":                  true,
	"Nepal":                    true,
	"Netherlands":              true,
	"New Caledonia":            true,
	"New Zealand":              true,
	"Nicaragua":                true,
	"Niger":                    true,
	"Nigeria":                  true,
	"North Korea":              true,
	"Norway":                   true,
	"Oman":                     true,
	"Pakistan":                 true,
	"Palestine":                true,
	"Panama":                   true,
	"Papua New Guinea":         true,
	"Paraguay":                 true,
	"Peru":                     true,
	"Philippines":              true,
	"Poland":                   true,
	"Portugal":                 true,
	"Puerto Rico":              true,
	"Qatar":                    true,
	"Romania":                  true,
	"Russia":                   true,
	"Rwanda":                   true,
	"S. Sudan":                 true,
	"Saudi Arabia":             true,
	"Senegal":                  true,
	"Serbia":                   true,
	"Sierra Leone":             true,
	"Slovakia":                 true,
	"Slovenia":                 true,
	"Solomon Is.":              true,
	"Somalia":                  true,
	"Somaliland":               true,
	"South Africa":             true,
	"South Korea":              true,
	"Spain":                    true,
	"Sri Lanka":                true,
	"Sudan":                    true,
	"Suriname":                 true,
	"Sweden":                   true,
	"Switzerland":              true,
	"Syria":                    true,
	"Taiwan":                   true,
	"Tajikistan":               true,
	"Tanzania":                 true,
	"Thailand":                 true,
	"Timor-Leste":              true,
	"Togo":                     true,
	"Trinidad and Tobago":      true,
	"Tunisia":                  true,
	"Turkey":                   true,
	"Turkmenistan":             true,
	"Uganda":                   true,
	"Ukraine":                  true,
	"United Arab Emirates":     true,
	"United Kingdom":           true,
	"United States of America": true,
	"Uruguay":                  true,
	"Uzbekistan":               true,
	"Vanuatu":                  true,
	"Venezuela":                true,
	"Vietnam":                  true,
	"W. Sahara":                true,
	"Yemen":                    true,
	"Zambia":                   true,
	"Zimbabwe":                 true,
	"eSwatini":                 true,
}

// mapCountryAliases maps what a model actually writes onto what the atlas
// calls it. Natural Earth's names are cartographer's names — "United States of
// America", "Dem. Rep. Congo", "Bosnia and Herz." — and no model emits those
// unprompted. Without this the commonest countries in any explainer are the
// ones that fail to render.
var mapCountryAliases = map[string]string{
	"usa":                              "United States of America",
	"us":                               "United States of America",
	"united states":                    "United States of America",
	"america":                          "United States of America",
	"uk":                               "United Kingdom",
	"great britain":                    "United Kingdom",
	"britain":                          "United Kingdom",
	"south korea":                      "South Korea",
	"korea":                            "South Korea",
	"north korea":                      "North Korea",
	"drc":                              "Dem. Rep. Congo",
	"democratic republic of the congo": "Dem. Rep. Congo",
	"congo":                            "Dem. Rep. Congo",
	"bosnia":                           "Bosnia and Herz.",
	"bosnia and herzegovina":           "Bosnia and Herz.",
	"czech republic":                   "Czechia",
	"czechia":                          "Czechia",
	"uae":                              "United Arab Emirates",
	"ivory coast":                      "Côte d'Ivoire",
	"cote d'ivoire":                    "Côte d'Ivoire",
	"central african republic":         "Central African Rep.",
	"south sudan":                      "S. Sudan",
	"dominican republic":               "Dominican Rep.",
	"equatorial guinea":                "Eq. Guinea",
	"solomon islands":                  "Solomon Is.",
	"falkland islands":                 "Falkland Is.",
	"western sahara":                   "W. Sahara",
	"myanmar":                          "Myanmar",
	"burma":                            "Myanmar",
	"russia":                           "Russia",
	"turkey":                           "Turkey",
	"swaziland":                        "eSwatini",
	"eswatini":                         "eSwatini",
	// Natural Earth 110m still calls it "Macedonia": the country renamed itself
	// in 2019 and a model will write the current name.
	"macedonia":       "Macedonia",
	"north macedonia": "Macedonia",
}
