package pipeline

// Companion ebook: one print-styled HTML document (cover, TOC, per-lesson
// transcripts + diagrams + quizzes, answer key appendix) printed to PDF via
// the same headless Chromium rod already provisions for diagram QA.

import (
	"context"
	"fmt"
	"html"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/proto"

	"github.com/enfec/coursesmith/internal/project"
)

// transcriptHeadingRe matches "## Title [M:SS]" transcript headings.
var transcriptHeadingRe = regexp.MustCompile(`^## (.+) \[(\d+:\d\d(?::\d\d)?)\]$`)

// ebookCSS is the print stylesheet. Documented choices: A4 with generous
// margins, lesson starts on a fresh page, code and tracebacks keep
// monospace, diagrams scale to the text column.
const ebookCSS = `
@page { size: A4; margin: 22mm 18mm; }
* { box-sizing: border-box; }
body { font: 11pt/1.55 Georgia, 'Times New Roman', serif; color: #1a1a1a; margin: 0; }
.cover { page-break-after: always; text-align: center; padding-top: 70mm; }
.cover h1 { font-size: 30pt; margin: 0 0 8mm; }
.cover p.desc { font-size: 12pt; color: #444; max-width: 120mm; margin: 0 auto 12mm; }
.cover p.meta { color: #888; font-size: 10pt; }
.toc { page-break-after: always; }
.toc h2 { font-size: 16pt; }
.toc ol { padding-left: 1.2em; }
.toc li { margin: 2mm 0; }
.lesson { page-break-before: always; }
h1.lesson-title { font-size: 20pt; border-bottom: 2pt solid #1a1a1a; padding-bottom: 2mm; }
h2 { font-size: 13pt; margin-top: 8mm; }
h2 .ts { color: #999; font-weight: normal; font-size: 9pt; }
p { margin: 2.5mm 0; text-align: justify; }
figure { margin: 6mm 0; text-align: center; page-break-inside: avoid; }
figure svg { max-width: 100%; height: auto; }
figcaption { font-size: 9pt; color: #666; margin-top: 1.5mm; }
.quiz { margin-top: 8mm; page-break-inside: avoid; }
.quiz h2 { border-top: 1pt solid #ccc; padding-top: 4mm; }
.question { margin: 4mm 0; page-break-inside: avoid; }
.question .qtype { font-size: 8pt; text-transform: uppercase; letter-spacing: .08em; color: #888; }
.question ol { list-style: upper-alpha; padding-left: 1.6em; margin: 1.5mm 0; }
pre { font: 9pt/1.4 'SF Mono', Menlo, Consolas, monospace; background: #f4f4f4;
      padding: 3mm; border-radius: 2pt; white-space: pre-wrap; page-break-inside: avoid; }
.appendix { page-break-before: always; }
.answer { margin: 2mm 0; }
`

// buildEbookHTML composes the whole book as one HTML document.
func buildEbookHTML(course *project.Course, lessons []*project.Lesson) (string, error) {
	var b strings.Builder
	b.WriteString(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>`)
	b.WriteString(html.EscapeString(course.Name))
	b.WriteString(`</title><style>` + ebookCSS + `</style></head><body>`)

	// Cover.
	fmt.Fprintf(&b, `<div class="cover"><h1>%s</h1><p class="desc">%s</p><p class="meta">Generated by coursesmith · %d lessons</p></div>`,
		html.EscapeString(course.Name), html.EscapeString(strings.TrimSpace(course.Description)), len(lessons))

	// TOC.
	b.WriteString(`<div class="toc"><h2>Contents</h2><ol>`)
	for _, l := range lessons {
		fmt.Fprintf(&b, `<li>%s</li>`, html.EscapeString(l.FrontMatter.Title))
	}
	b.WriteString(`<li>Appendix: Quiz answer key</li></ol></div>`)

	// Lessons.
	type answerRow struct {
		lesson   string
		question string
		answer   string
	}
	var answers []answerRow
	for _, l := range lessons {
		fmt.Fprintf(&b, `<div class="lesson"><h1 class="lesson-title">%s</h1>`, html.EscapeString(l.FrontMatter.Title))

		// Transcript: "# title" is skipped (the lesson title heads the
		// chapter), "## X [M:SS]" becomes a timestamped heading.
		transcript, err := os.ReadFile(filepath.Join(l.GeneratedDir(), TranscriptFileName))
		if err != nil {
			fmt.Fprintf(&b, `<p><em>Transcript not generated yet — run the pipeline for %s.</em></p>`, html.EscapeString(l.ID))
		} else {
			diagramsUsed := map[string]bool{}
			sectionDiagrams := sectionDiagramMap(l)
			for _, block := range strings.Split(strings.ReplaceAll(string(transcript), "\r\n", "\n"), "\n\n") {
				block = strings.TrimSpace(block)
				switch {
				case block == "" || strings.HasPrefix(block, "# "):
					continue
				case strings.HasPrefix(block, "## "):
					line := strings.SplitN(block, "\n", 2)[0]
					if m := transcriptHeadingRe.FindStringSubmatch(line); m != nil {
						fmt.Fprintf(&b, `<h2>%s <span class="ts">%s</span></h2>`, html.EscapeString(m[1]), m[2])
						// Inline this section's diagrams right under its heading.
						slug := slugify(m[1])
						for _, id := range sectionDiagrams[slug] {
							if diagramsUsed[id] {
								continue
							}
							diagramsUsed[id] = true
							if svg, err := os.ReadFile(filepath.Join(l.GeneratedDir(), DiagramsDirName, id+".svg")); err == nil {
								fmt.Fprintf(&b, `<figure>%s<figcaption>%s</figcaption></figure>`, string(svg), html.EscapeString(id))
							}
						}
					} else {
						fmt.Fprintf(&b, `<h2>%s</h2>`, html.EscapeString(strings.TrimPrefix(line, "## ")))
					}
				default:
					fmt.Fprintf(&b, `<p>%s</p>`, html.EscapeString(block))
				}
			}
		}

		// Quiz (merged with human overrides), answers withheld to the appendix.
		if quiz, _, _, err := LoadQuizWithOverrides(l); err == nil && quiz != nil {
			fmt.Fprintf(&b, `<div class="quiz"><h2>%s</h2>`, html.EscapeString(quiz.Title))
			for i, q := range quiz.Questions {
				fmt.Fprintf(&b, `<div class="question"><div class="qtype">%s</div><p><strong>%d.</strong> %s</p><ol>`,
					html.EscapeString(q.Type), i+1, formatQuestionPrompt(q.Prompt))
				for _, opt := range q.Options {
					fmt.Fprintf(&b, `<li>%s</li>`, html.EscapeString(opt))
				}
				b.WriteString(`</ol></div>`)
				answers = append(answers, answerRow{
					lesson:   l.FrontMatter.Title,
					question: fmt.Sprintf("%d", i+1),
					answer: fmt.Sprintf("%s — %s",
						string(rune('A'+q.AnswerIndex)), strings.TrimSpace(q.Explanation)),
				})
			}
			b.WriteString(`</div>`)
		}
		b.WriteString(`</div>`)
	}

	// Answer key appendix.
	b.WriteString(`<div class="appendix"><h1 class="lesson-title">Appendix: Quiz answer key</h1>`)
	current := ""
	for _, a := range answers {
		if a.lesson != current {
			current = a.lesson
			fmt.Fprintf(&b, `<h2>%s</h2>`, html.EscapeString(current))
		}
		fmt.Fprintf(&b, `<p class="answer"><strong>%s.</strong> %s</p>`, a.question, html.EscapeString(a.answer))
	}
	b.WriteString(`</div></body></html>`)
	return b.String(), nil
}

// sectionDiagramMap maps section id → diagram ids cued in that section.
func sectionDiagramMap(l *project.Lesson) map[string][]string {
	out := map[string][]string{}
	script, err := loadScript(l)
	if err != nil {
		return out
	}
	for _, sec := range script.Sections {
		for _, cue := range sec.Cues {
			if cue.Type == CueDiagram {
				out[sec.ID] = append(out[sec.ID], cue.Ref)
			}
		}
	}
	return out
}

// formatQuestionPrompt renders a quiz prompt: fenced code becomes <pre>,
// the rest is escaped text.
func formatQuestionPrompt(prompt string) string {
	parts := strings.Split(prompt, "```")
	var b strings.Builder
	for i, part := range parts {
		if i%2 == 0 {
			b.WriteString(html.EscapeString(strings.TrimSpace(part)))
			continue
		}
		code := part
		if j := strings.IndexByte(code, '\n'); j >= 0 {
			code = code[j+1:] // drop the language tag line
		}
		fmt.Fprintf(&b, `<pre>%s</pre>`, html.EscapeString(strings.TrimSpace(code)))
	}
	return b.String()
}

// BuildEbook renders the course PDF to courses/<slug>/generated/<slug>.pdf
// and returns its path.
func BuildEbook(ctx context.Context, e *Env, course *project.Course) (string, error) {
	lessons, err := course.Lessons()
	if err != nil {
		return "", err
	}
	doc, err := buildEbookHTML(course, lessons)
	if err != nil {
		return "", err
	}

	outDir := filepath.Join(course.Dir, CourseGeneratedDirName)
	htmlPath := filepath.Join(outDir, course.Slug+"-ebook.html")
	if err := writeFileAtomic(htmlPath, []byte(doc)); err != nil {
		return "", err
	}

	fmt.Fprintf(e.out(), "  → ebook     printing %d lesson(s) to PDF via headless Chromium...\n", len(lessons))
	pdf, err := printHTMLToPDF(ctx, htmlPath)
	if err != nil {
		return "", err
	}
	pdfPath := filepath.Join(outDir, course.Slug+".pdf")
	if err := writeFileAtomic(pdfPath, pdf); err != nil {
		return "", err
	}
	return pdfPath, nil
}

// printHTMLToPDF prints a local HTML file with headless Chromium (rod).
func printHTMLToPDF(ctx context.Context, htmlPath string) (out []byte, err error) {
	defer func() {
		if rec := recover(); rec != nil {
			err = fmt.Errorf("printing PDF: %v", rec)
		}
	}()
	launchURL, err := launcher.New().Headless(true).Launch()
	if err != nil {
		return nil, fmt.Errorf("launching headless Chromium: %w", err)
	}
	browser := rod.New().ControlURL(launchURL)
	if err := browser.Connect(); err != nil {
		return nil, fmt.Errorf("connecting to headless Chromium: %w", err)
	}
	defer browser.Close()

	abs, err := filepath.Abs(htmlPath)
	if err != nil {
		return nil, err
	}
	page, err := browser.Page(proto.TargetCreateTarget{URL: "file://" + abs})
	if err != nil {
		return nil, fmt.Errorf("opening ebook page: %w", err)
	}
	defer page.Close()
	page = page.Timeout(2 * time.Minute).Context(ctx)
	if err := page.WaitLoad(); err != nil {
		return nil, fmt.Errorf("loading ebook page: %w", err)
	}
	reader, err := page.PDF(&proto.PagePrintToPDF{
		PrintBackground:   true,
		PreferCSSPageSize: true,
	})
	if err != nil {
		return nil, fmt.Errorf("printing to PDF: %w", err)
	}
	data, err := io.ReadAll(reader)
	if err != nil {
		return nil, fmt.Errorf("reading PDF stream: %w", err)
	}
	return data, nil
}
