#!/usr/bin/env python3
"""One original title per module, keyed by module number in plan.json.

`lines` are the two lines of the title card; a *word* between asterisks is
emphasised by the head slide, the same syntax every other deck in this library
uses. `stamp` is the small line under it - the module's contents in the house
lower-case-with-middots style.

These are ours. The lecture titles in `MANIFEST.md` for Weeks 1-2 are the
reference course's, which `QA.md` flags as something to rewrite; nothing here
reuses them.
"""

M = {
 1: (["Day one,", "from *nothing*"],
     "install cursor  ·  build a 3d game  ·  the missing manual"),
 2: (["What *vibe coding*", "actually means"],
     "the roadmap  ·  agents vs coders  ·  the eight stages"),
 3: (["What is *happening*", "in there"],
     "tokens, memory and reasoning  ·  tools, loops and agents"),
 4: (["Context is the", "*whole* game"],
     "system prompts and the context window  ·  writing agents.md"),
 5: (["From *YOLO* to", "Ralph loops"],
     "the workflow ladder  ·  comparing the models on the numbers"),
 6: (["Hands on the", "*keys*"],
     "four ides, one build  ·  the settings that matter  ·  cursor in yolo mode"),
 7: (["The same app,", "in *Copilot*"],
     "one build, start to finish, in vs code"),
 8: (["*Codex* takes it", "zero-shot"],
     "the whole kanban app from a single prompt"),
 9: (["*Antigravity*,", "and the verdict"],
     "gemini 3 pro  ·  cursor vs copilot vs codex vs antigravity"),
10: (["Be the *boss*"],
     "choosing the model for the job  ·  five principles that hold"),
11: (["Responsible", "*YOLO*"],
     "setting up openrouter  ·  a next.js site with codex in cursor"),
12: (["A *twin*, and a", "second opinion"],
     "an ai chat wired to openrouter  ·  code review across two models"),
13: (["From a toy to", "a *product*"],
     "karpathy's rules  ·  front end, back end, apis and docker"),
14: (["*Scaffold* it", "properly"],
     "standing up the project  ·  planning before generating"),
15: (["*Docker*, FastAPI,", "and the build"],
     "the kanban app comes together"),
16: (["Debug it,", "then *ship* it"],
     "drag and drop, fixed  ·  week one wrap"),
17: (["Enter *vibe", "engineering*"],
     "from coding to engineering  ·  installing claude code"),
18: (["*Claude Code*,", "first run"],
     "init, context and a test  ·  fixing a hallucination"),
19: (["The *free*", "alternatives"],
     "opencode and glm 4.7  ·  amp code, openrouter and ollama"),
20: (["Learn the", "*controls*"],
     "commands, shortcuts, configuration  ·  sessions and git"),
21: (["*Rewind*, bypass,", "and loop"],
     "checkpoints and rewind  ·  yolo mode  ·  ralph loops"),
22: (["*MCP*, skills", "and plugins"],
     "the big three  ·  what an mcp server really is"),
23: (["Wiring it *up*"],
     "context7 and polygon io  ·  skills, the simpler way"),
24: (["The skill", "*marketplace*"],
     "installing agent browser in claude code"),
25: (["*Plugins*, and", "how to choose"],
     "the plugin marketplace  ·  mcp vs skills vs plugins"),
26: (["A *real* team", "workflow"],
     "claude code, jira and mcp  ·  wiring it to jira"),
27: (["From a *ticket*", "to a pull request"],
     "the github mcp server  ·  autonomy, end to end"),
28: (["A whole app,", "from one *ticket*"],
     "next.js from a jira issue  ·  a disciplined way to debug"),
29: (["Build a *SaaS*"],
     "skills and claude.md  ·  writing a custom skill"),
30: (["Tickets in,", "*features* out"],
     "filing v1  ·  building with claude code and fastapi"),
31: (["*Test* it,", "then merge"],
     "the legal doc generator  ·  final pr, full demo, week two"),
32: (["When you stop", "*typing*"],
     "the brief  ·  slash commands  ·  sub-agents  ·  hooks"),
33: (["*Package* it,", "then contain it"],
     "plugins and marketplaces  ·  why sandboxing is the unlock"),
34: (["*Scale*, and the", "Agent SDK"],
     "the seven rules for a big codebase  ·  driving claude from code"),
35: (["No *screen*", "at all"],
     "the print flag  ·  agents in a pipeline  ·  a stack of documents"),
36: (["A *team*, not", "an assistant"],
     "sub-agents vs teams  ·  the roster  ·  seven agents, one task list"),
37: (["What the *swarm*", "actually did"],
     "the evidence in the repo  ·  the integration pass  ·  your own orchestrator"),
38: (["Nobody in", "the *chair*"],
     "a second brief  ·  turning the orchestrator into a pipeline"),
39: (["The *unattended*", "run"],
     "agents building with no terminal to watch"),
40: (["What a *program*", "built"],
     "the first run  ·  what is wrong with it  ·  the fix pass"),
41: (["Somewhere other", "than your *laptop*"],
     "the repo and its ci  ·  an issue with an address  ·  the pull request"),
42: (["Two products,", "and a *wrap*"],
     "the history the pipeline lost  ·  honestly compared  ·  ship it"),
}
